### PR TITLE
ci: Add black formatter to `ci.yml`

### PR DESCRIPTION
**Pull request by BlenderDefender**
Check, whether the files are formatted properly using the black formatter when changes are pushed or pull requests are opened.

### CODE REVIEW

**Comment by Andrej730** [comment]
Hi! `ci.yml` is triggered only on the changes in ifcopenshell and in some related packages. I think we can create a separate workflow for this so it can cover more packages (e.g. including blenderbim).

**Comment by BlenderDefender** [comment]
How should that seperate workflow be called? Something like `linter.yml`?

**Comment by Andrej730** [comment]
> How should that seperate workflow be called? Something like `linter.yml`?

We can call it something like `ci-black-formatting.yml`/`ci-black-formatter.yml` so it won't get confused with pylint.

**Comment by BlenderDefender** [comment]
Alright, done 👍

**Comment by Andrej730** [comment]
Is there a way to set it up so it would check either only changes in the last commit or files affected by the last commit? 
We have a huge repo and this way we'll be able to properly format it in more gradual way 😁

**Comment by Moult** [comment]
I evilly ran black on everything and now we pass :D

MUAHAHAHAHAHA

**Comment by Andrej730** [comment]
rip git blame

**Pull request merged**
