### PR TITLE
IfcConvert --filter-file & --no-progress

### PR DESCRIPTION
**Pull request by Stinkfist0**
I found myself often crafting the filtering commands in notepad and copy-pasting them to command-line so I thought why not offer a support for reading them from a file.  The second new option can be very useful when directing the output of IfcConvert to a log file.

### CODE REVIEW

**Comment by aothms** [comment]
I agree that writing to stdout there is an awkward choice. But it could already be toggled with an (obscure) existing method [1]. I.e. `if (...) { Logger::SetOutput(NULL, &log_stream); }` at [2]. Not saying it is particularly elegant that way, but no need for these boolean flags either.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcLogger.cpp#L34
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/IfcConvert.cpp#L410

**Comment by Stinkfist0** [comment]
Thanks for the feedback, I'll rework the solution as per your suggestion. Does `--filter-file` look OK?

**Comment by aothms** [comment]
> Does --filter-file look OK?

Looks ok to me. I can imagine sth like a reusable configuration would come in handy if you need work with IfcConvert a lot. Ideally I think these commands would use the same flag, sth like (purely hypothetical) `--filter "include(entity(IfcWall) or attribute(ObjectType=seinä))"` and `--filter @my_file.txt`. Especially if you can apply these filter flags to IFC output files as well, i.e get subsets of IFC models, it gets even more useful perhaps. Anyway, just random thoughts.

**Comment by Stinkfist0** [comment]
Yeah, I've toyed around with similar ideas in my head. Also being able to specify multiple output files, e.g. one per representation layer or a storey, in a single go would be really nice at some point.

**Comment by Stinkfist0** [comment]
Suppressing IfcFile::Init() prints done suggested.

**Comment by aothms** [comment]
Thanks, sorry for the delay

**Pull request merged**
