### PR TITLE
async iterator init

### PR DESCRIPTION
**Pull request by aothms**
#1866

### CODE REVIEW

**Comment by aothms** [comment]
Ugh that was a nasty one. I'm really bad a multi threading in C++, but it's actually a slight improvement now, because at least I could eliminate the progress printing functions in iterator, and use the normal one in IfcConvert.

C++ has nice futures and promises, but the stupid thing is that we still have the requirement that we only return tasks that have succeeded, this requires a lot of waiting and because we don't know in advance how many tasks succeed we also can't use vanilla features that well. So in the end I used a synchronized list and a loop in the main thread to catch the elements added to the list. It looks dirty, but maybe it isn't so bad. It does mean there is yet another thread active (not sure if it matters), so there is the N worker threads, a thread to manage those, and a thread to respond to get() and next() calls.

@Moult can you help test a bit and review? Thanks.


~~~
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open("../nibs/duplex/Duplex_MEP_20110907_optimized.ifc")
it = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f, num_threads=8)

assert set(it.progress() for _ in ifcopenshell.geom.consume_iterator(it)) == set(range(101))

print("Yay")
~~~

**Comment by aothms** [comment]
@sanderboer hope you're well, since this is your original work also, I thought I'd CC you just in case you want to have a look and offer feedback. It's still your original threadpool, but started using std::async() so that the main thread can watch a std::list of results grow.

**Comment by aothms** [comment]
If no comments, I'm just going to merge this before it goes stale.

**Comment by Moult** [comment]
So sorry, I've been swamped. I will test it :)

**Pull request merged**
