### PR TITLE
Fix minor bug

### PR DESCRIPTION
**Pull request by maxfb87**
Related to #2825, have been created others panels or operators that haven't the is_regitered method so there was a new error in blender console.
So i found a better and cleaner method to solve the problem also in case of, in the future, there would be new similar problems.

### CODE REVIEW

**Comment by maxfb87** [comment]
@Andrej730 i have seen your commit here https://github.com/IfcOpenShell/IfcOpenShell/commit/e71ee988bf45510a009d0c46ead7aa0a2f4e9d63

Maybe this is better?
The problem here was that if a module is not visible, it is unregistered two times causing the error...

**Comment by Andrej730** [comment]
Sure, it will work.
Btw any ideas why did the original error with unregistered modules occured? I thought we import all modules in `bim/__init__.py` so it shouldn't happen. Currently it still might occur for classes based on Gizmo, GizmoGroup, Macro if they were not registered for some reason.

**Comment by maxfb87** [comment]
Yes, i think that the original error was found as a side effect of #2825.
If you look at the video shared, you'll see that there was an error in console line.
I tried to solve it in a previous PR, but i think that something can be done.

Basically the issue is when a module is not visible: this module is unregisted too so, on exit, blender tries to unregister a module that is already unregistered.
From this perspective, i think that the method ".is_registered" is suited to check if a module is already unregistered or not but not every cls has the method ".is_registered".
So i did a sort of workaround a few weeks ago but yesterday a saw the new bug and i did this PR that, i think, it's more general and cleaner.

**Comment by Andrej730** [comment]
kk, merged it, just was curious to pin down why classes appear to be unregistered.
thank you for the contribution.

**Pull request merged**
