### PR TITLE
Update selector.py

### PR DESCRIPTION
**Pull request by bbrangeo**
Change l 188

value = filter_rule.children[2].children[0] in ["TRUE", "true"]

### CODE REVIEW

**Comment by aothms** [comment]
Thanks. From the grammar I see:

BOOLEAN: "TRUE" | "FALSE" | "true" | "false"| "True" | "False"

So probably add 'True' or `filter_rule.children[2].children[0].lower() == 'true'`?

**Comment by bbrangeo** [comment]
Yes thanks

**Comment by bbrangeo** [comment]
filter_rule.children[2].children[0].lower() == 'true' is perfect

**Comment by bbrangeo** [comment]
Thanks

**Pull request closed without merging**
