### PR TITLE
V0.6.0

### PR DESCRIPTION
**Pull request by Hasashi**
Its seems like npcglip.org has updated to https. This should be changed in the build-deps file.

### CODE REVIEW

**Comment by thorade** [comment]
Thanks for the Pull Request. I am afraid something went wrong, because if you look at the changes, you are suggesting to merge the v0.6 branch into the master. But what you probably really wanted to do is fork the repository, create a new branch starting from master, do the http to https change, and send a PR for that change.
The easiest way would probably to do it using the web interface: Just go to the file, clicke the pencil/edit button and change diretly in the web interface.

**Comment by aothms** [comment]
Indeed these are changes for the upcoming 0.6 version to enable working with ifc2x3 and ifc4 in the same executable. Better not merge into master yet.

**Comment by Hasashi** [comment]
Thanks for the explanation. I was not familiar with pull request but wanted to contribute to your great work. Unfortionally I could not find out how to undo my mess. Sorry for the inconvinience.

**Comment by aothms** [comment]
Don't worry, no harm done. Contributions very welcome indeed :)

**Pull request closed without merging**
