### PR TITLE
Attempt for compatibility with PythonOCC 7.4.1

### PR DESCRIPTION
**Pull request by ManuelFDS**
Used import statement from occ_utils.py 
added an If-Statement to the GetObject()-call.

Calling SetSelectionPriority directly on ais, as proposed by aothms (https://github.com/IfcOpenShell/IfcOpenShell/issues/1098) did not work.
Could load some ifc-models but needs further testing.

### CODE REVIEW

**Comment by ManuelFDS** [comment]
Worked so far but got follwing Error, when turning model without selecting a Element:
property set dictionary has 1036 entries
Traceback (most recent call last):
  File "C:\Anaconda3\envs\IFC\lib\site-packages\OCC\Display\qtDisplay.py", line 234, in mouseReleaseEvent
    self._display.Select(pt.x(), pt.y())
  File "C:\Anaconda3\envs\IFC\lib\site-packages\ifcopenshell\geom\app.py", line 568, in HandleSelection
    v.Select()
  File "C:\Anaconda3\envs\IFC\lib\site-packages\OCC\Core\AIS.py", line 6373, in Select
    return _AIS.AIS_InteractiveContext_Select(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'AIS_InteractiveContext_Select'.
  Possible C/C++ prototypes are:
    AIS_InteractiveContext::Select(Standard_Integer const,Standard_Integer const,Standard_Integer const,Standard_Integer const,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(TColgp_Array1OfPnt2d const &,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(Standard_Boolean const)

I suppose this is thrown by AIS because there is no element selected!
There should be a function call inserted to select a element where I inserted the conditional statement.

Which function could be called?

**Comment by aothms** [comment]
`AIS_InteractiveContext::Select()` processes the selection event based on mouse coords (that it has registered already). So we need to select this prototype: `AIS_InteractiveContext::Select(Standard_Boolean const)`. https://dev.opencascade.org/doc/refman/html/class_a_i_s___interactive_context.html#a19a654f1ee2c6988b1a04c6ff15d2e61 So the boolean indicates whether to update the display of the viewer. Should be `True` I guess.

Thanks for your work so far :)

**Comment by tpaviot** [comment]
I confirm @aothms diagnostic

**Comment by jakob-beetz** [comment]
I have gotten partial selection working with a modified `ifcopenshell.geom.app.py` 
Thanks to @tpaviot [0.18 -> 7.4.1 migration guide](https://github.com/tpaviot/pythonocc-core/wiki/Porting-from-0.18.x-to-7.4.0) it was a breeze. 

See https://github.com/jakob-beetz/IfcOpenShellScriptingTutorial/releases/ 

Its just a few lines that need changes. Should I submit a pull request or just some changes here?

**Comment by aothms** [comment]
Awesome @jakob-beetz I'll merge this one and then you can open one with your work :) Looking forward

**Pull request merged**
