### PR TITLE
Compute wall net quantities

### PR DESCRIPTION
**Pull request by Gorgious56**
This aims to fix the wall quantities computation not taking into account modifiers (and by extension openings).

### CODE REVIEW

**Comment by Moult** [comment]
This is good except that gross vs net isn't as simple as "are modifiers applied". IfcOpenShell by default computes the net geometry. During editing, users selectively convert these baked net geometry into gross geometry + boolean modifiers if they choose to do so.

It's still better than giving a zero everywhere, so merging :)

**Comment by Gorgious56** [comment]
@Moult Oh okay, then if I understand correctly, when the openings have been applied in Blender, the gross calculations will be off. Is it possible to get back the gross quantities from ifcopenshell or the ifc contents ? Should we be using ifcopenshell directly then to compute the quantities ?

**Comment by Moult** [comment]
> when the openings have been applied in Blender, the gross calculations will be off. 

Correct.

> Is it possible to get back the gross quantities from ifcopenshell or the ifc contents ? Should we be using ifcopenshell directly then to compute the quantities ?

Yes, we can either recreate the geometry using IfcOpenShell, calculate using IfcOpenShell directly, or do some checks in Blender whether or not there are openings and make an informed decision. I'm also not sure how fast it is, or exactly what code it should be to calculate directly in IfcOpenShell unfortunately, hence the TODO.

**Comment by aothms** [comment]
I think it was already possible with some low level trickery but I just mapped them to top level properties:

~~~
>>> import ifcopenshell
>>> import ifcopenshell.geom
>>> f = ifcopenshell.open("acad2010_walls.ifc")
>>> it = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f)
>>> it.initialize()
True
>>> elem = it.get_native()
>>> elem.surface_area
10.220161925180994
>>> elem.volume
0.9425983811263172
~~~

**Pull request merged**
