### PR TITLE
Use a fixed revision of OpenCOLLADA...

### LINKED ISSUE #36: IfcConvert generates DAE that crashes Collada Importers
VS 2015 x64 RelWithDebInfo build:
`IfcConvert.exe ..\..\test\input\acad2010_objects.ifc acad2010_objects.dae`
Both ViewFBX and Unity will crash when trying to open the file. The crash seems to occur with all possible input files. OBJ works fine. OpenCOLLADAValidator tells the file to be valid.

I have been using mostly my old SourgeForge-based fork and noticed this now when testing the official repo/fork as I wanted to test the fixes in IfcMappedItem surfaces styles.

### PR DESCRIPTION
**Pull request by Stinkfist0**
in order to prevent introducing breaking changes. Closes #36, related to #38

### CODE REVIEW

**Comment by Stinkfist0** [comment]
The *nix build script seems to use pretty old revision - maybe good to update it to the same revision if possible?

**Comment by aothms** [comment]
This didn't update the repo on my local machine because it was already cloned. Can you do a `git checkout` in the ELSE branch as well?

**Comment by Stinkfist0** [comment]
Ah, yes this assumed nuking the old clone completely.

**Comment by Stinkfist0** [comment]
Does this look OK now?

**Comment by aothms** [comment]
Sorry for the slow replies these days. Thanks again!

**Pull request merged**
