### PR TITLE
Minor UX and documentation tweaks

### PR DESCRIPTION
**Pull request by globalcitizen**
- Normalize UX panel names to BIM/IFC prefix.
 - Minor documentation updates

### CODE REVIEW

**Comment by Moult** [comment]
I agree it is desirable to normalise the UI panel naming. However, I'm not a fan of "BIM/IFC" everywhere. A better solution is to use IFC when the panel is IFC specific, and BIM when it applies to IFC as well as other BIM concepts.

IFC is one of a few related, but separate BIM standards, others include BCF (BIM Collaboration Format - therefore renaming BIM/IFC Collaboration is incorrect), MVD (Model View Definitions - which currently mostly include IFC, but may not always).

Therefore I propose:
 - IFC Object
 - IFC Documents
 - IFC Representations
 - IFC Classification References
 - IFC Property Sets (no Item)
 - IFC Classifications
 - IFC Representations
 - IFC Materials
 - IFC Georeferencing
 - BIM Documentation
 - IFC Owner History
 - IFC Geometric Representation Contexts
 - Building Information Modeling <-- leave as is for now, better to split into two panels, and the classification portion of it can be reorganised elsewhere I think
 - IFC Search
 - IFC CSV Import/Export
 - BIM Collaboration Format (BCF)
 - BIMTester Quality Auditing
 - IFC BIM Server Library
 - IFC Diff
 - Model View Definitions (MVD)
 - IFC Clash Sets

Perhaps also update the docs to specifically talk about the details of #860? i.e. that it is specific to a particular ubuntu package?

**Comment by globalcitizen** [comment]
OK how's this one?

**Comment by Moult** [comment]
Looks great. Merge now, or wait for more changes?

**Comment by globalcitizen** [comment]
Merge now, I will get back to functional testing.

Next time maybe look at enable/disable checkboxes and UI visibility changes for IFC and BCF.

**Pull request merged**
