### PR TITLE
Add gross volume calculation

### PR DESCRIPTION
**Pull request by maxfb87**
Added gross volume calculation.
The procedure basically creates a new ifc object without voids of the original one and calculate that volume, so the function works only if the object has voids.
Not sure if it is the correct method or the best method, but it functions and i think that it could be considered native ifc.

### CODE REVIEW

**Comment by Moult** [comment]
Why are you creating a new IFC entity? Can't you just use the old entity? If you want to calculate the body without openings, just disable opening subtractions: https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html#disable-opening-subtractions as one of the iterator settings.

Also don't use the from_pydata, it's much slower and a better method is to use foreach_set (see example in import_ifc.py).

**Comment by maxfb87** [comment]
@Moult done and done, thanks for the suggestions ... :-) btw, what do you think about this approach? Is it correct?

**Comment by Moult** [comment]
That should work! Is it necessary to create the Blender object? Can you just create a mesh?

BTW this should be heavily simplified if/when @aothms or someone helps expose the already pre-calculated values from IOS e.g. https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html#validate-quantities or https://github.com/IfcOpenShell/IfcOpenShell/issues/1040

**Comment by maxfb87** [comment]
@Moult yep, i've removed the object, so now bmesh is used to calculate the volume.
I used the object because, in this way, i could use the self.net_volume() function so, if changes the net_volume calculation, changes also the gross_volume.

**Pull request merged**
