### PR TITLE
Updated *nix build script to also support git pull repository for dependencies + Support for IFC4x1 added

### PR DESCRIPTION
**Pull request by atibaut**
Motivated by issue #608 to improve the method def git_clone(...) to the def git_clone_or_pull_repository(...). 
Also, dependencies versions were updated.

### CODE REVIEW

**Comment by aothms** [comment]
Thanks this looks really comprehensive. I have some doubts though about the update to Swig 4. It seems there are some assumptions in the code that won't work with that version, see https://github.com/IfcOpenShell/IfcOpenShell/issues/582#issuecomment-497789849 Were there specific reasons for that particular update or can you revert that?

**Comment by atibaut** [comment]
@aothms reverted to SWIG_VERSION=4.0.0.

**Comment by aothms** [comment]
Thanks, in addition I cannot find the libxml2 version you specified at ftp://xmlsoft.org/libxml2/ so the build currently fails. Where did you find it? `2.9.9` is there, but not `2.9.9_2`.

**Comment by aothms** [comment]
I'll change it back to `2.9.9` after merging. Thanks again for your efforts on this.

**Pull request merged**
