### PR TITLE
when bpy.ops.bim.object_duplicate_move_linked_aggregate is called fro…

### PR DESCRIPTION
**Pull request by brunoperdigao**
…m the panel, the new objects are placed based on the 3d cursor position

### CODE REVIEW

**Comment by brunoperdigao** [comment]
@theoryshaw It wasn't necessary to deal with context switching. It just introduces a vector calculation to get their new position based on the 3d cursor.

**Comment by theoryshaw** [comment]
Nice!, i love how this works. 
The one adjustment i would suggest is to make sure it's basing the basepoint on the parent aggregate, not a child aggregate. 
Here's a visual:

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b664ff7f-b3ae-4fc8-ad2b-9de08244f232

**Comment by theoryshaw** [comment]
if you need a test file:
[aggregate test - Copy.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15237713/aggregate.test.-.Copy.ifc.txt)

**Comment by theoryshaw** [comment]
Whoops, also ran into error:


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/82b584ae-9aa9-4869-a1f8-3d6ba9fed0c3

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1137, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1324, in _execute
    old_to_new = DuplicateMoveLinkedAggregate.execute_ifc_duplicate_linked_aggregate_operator(self, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1117, in execute_ifc_duplicate_linked_aggregate_operator
    if self.location_from_3d_cursor:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy_types.py", line 939, in __getattribute__
    return super().__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RefreshLinkedAggregate' object has no attribute 'location_from_3d_cursor'

```

**Comment by brunoperdigao** [comment]
@theoryshaw Added a commit, both problems should be fixed.

**Comment by theoryshaw** [comment]
Whoops, missed this... will do!

**Pull request merged**
