### PR TITLE
MSVC Debug/Release CMake fixes

### PR DESCRIPTION
**Pull request by Stinkfist0**
Supersedes #201, thanks for the pointers.

### CODE REVIEW

**Comment by aothms** [comment]
Doesn't seem to work on Linux:

    make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/TKernel', needed by `examples/IfcOpenHouse'.  Stop.

Perhaps you need to include `get_filename_component(OCE_LIB_EXT ${libTKernel} EXT)`?

**Comment by Stinkfist0** [comment]
Hmm, weird. Maybe simply better I set up the Windows-Ubuntu dev env to test this properly instead of trying to fix bindly.

**Comment by Stinkfist0** [comment]
Ah, right, missing the lib-prefix for the filenames.

**Comment by Stinkfist0** [comment]
Should be good to go.

**Comment by aothms** [comment]
Great, many many thanks as always!

**Pull request merged**
