### PR TITLE
Update tooltips for UI elements

### PR DESCRIPTION
**Pull request by manuvarkey**
Related to https://github.com/IfcOpenShell/IfcOpenShell/issues/1646

### CODE REVIEW

**Comment by Moult** [comment]
Why are some of the labels blanked out?

**Comment by manuvarkey** [comment]
> Why are some of the labels blanked out?

@Moult 

When adding text to both `bl_label` and `bl_description` for operators with `text=""` (for ex. `row.operator("bim.edit_openings", icon="CHECKMARK", text="")`), both labels are displayed as tooltips. 

Screenshots given below.

Screenshot from 2024-09-07 21-45-56
Screenshot from 2024-09-07 22-09-35
Screenshot from 2024-09-07 22-14-34

For all other operators, I have added both labels.

**Comment by manuvarkey** [comment]
Adding `bl_label` alone shows `(undocumented operator)` message.

Screenshot from 2024-09-07 22-29-10

**Comment by Andrej730** [comment]
`bl_label` is important as it's the operator's name appearing in the operator search and quick favorites, so it shouldn't be empty. I think there is no way in Blender to avoid "(undocumented operator)" without providing any description - so we should provide one or keep "(undocumented operator)" for now.

**Comment by Moult** [comment]
Agreed, @manuvarkey do you mind ensuring that bl_label is never blank? If it duplicates the description, so be it until we find something even more descriptive. If you make a list of duplicates, I can also propose some descriptions. Happy to merge after these changes.

**Comment by Moult** [comment]
A minor nitpick not to change "Opening" to "Void". It is an "Opening" element in IFC - that is the exact jargon, the "Void" is a verb, the relationship between the opening and the building element.

**Comment by manuvarkey** [comment]
@Moult Made the suggested changes. I have added short identifiers for `bl_label` field in the above commits so as not to leave them blank.

**Comment by Moult** [comment]
Edit openings should make all temporary openings disappear and sync changes back to the building element.

**Pull request merged**
