### PR TITLE
Fix typo in docstring in ifcdiff.py

### PR DESCRIPTION
**Pull request by JohannesSchorr**
Changed „old“ to „new“ in description of new.

### CODE REVIEW

**Comment by Moult** [comment]
Thank you so much!

**Comment by Moult** [comment]
Oh, we're now on the v0.8.0 branch btw

**Comment by JohannesSchorr** [comment]
It was a pleasure. 
Grateful to contribute.

**Comment by JohannesSchorr** [comment]
@Moult: I was wondering if there is a need to add further documentation to the ifcdiff-Module? 
If so, please let me know. 
Kind regards

**Pull request merged**
