### PR TITLE
Improve error message when keyword not found. See #491.

### PR DESCRIPTION
**Pull request by Moult**
Better late than never. I didn't test it though, and I only added `+ s` for one of the error messages because I couldn't see how to do it for the other two.

### CODE REVIEW

**Comment by aothms** [comment]
Haha yeah wonder how long these have been in there.

**Comment by aothms** [comment]
We need to manually rerun the code gen afterwards though.

**Comment by Moult** [comment]
Yes I avoided rerunning the codegen as you mentioned you also might want to exclude those and make it part of the build system.

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/fe533077f47c1ada9a334cabb79dea9a631f779a

**Comment by aothms** [comment]
Let's save the build system changes for later

**Pull request merged**
