### PR TITLE
fix error on load an existing drawing layout created on a different os

### PR DESCRIPTION
**Pull request by maxfb87**
If a layout was created on windows and i try to load it on linux i get this error
image
This fix prevents this error

### CODE REVIEW

**Comment by Moult** [comment]
I think this has already been fixed.

**Comment by maxfb87** [comment]
Ah ok, i'll try and i'll write here, thanks

**Comment by Moult** [comment]
More specifically now drawings should always use / separators which works on all OSes. However if you have an older file prior to that update, it may contain \ separators and you need to update it manually.

**Comment by maxfb87** [comment]
@Moult i think that what you said is right for the drawings but sheets (or layouts) still have the bug... in fact, i tried to open a .ifc file on linux, created on windows, and the error still exists (latest BBim version in both os).
If you want to try, i attached the files created on windows
[checksheets.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11971558/checksheets.zip)

**Comment by maxfb87** [comment]
I noticed that the sheets (called also layouts) are stored in a different way then drawings... the drawings are stored like every other external document but sheets are not and sheets get the path from a w3c property...

**Comment by Moult** [comment]
Ah thanks you're right sheets have an additional check to store them as paths relative to the IFC model, so hopefully this is now actually fixed :)

**Pull request closed without merging**
