### PR TITLE
Unescaped ; was causing problems in Inkscape

### PR DESCRIPTION
**Pull request by FabioPiccinini**
An unescaped `;` was causing problems when opening svgs that included this style with Inkscape

### CODE REVIEW

**Comment by aothms** [comment]
This is in a comment, maybe instead reply `;` with `-` or `,` as it leaves the textual intent more in tact?

I think most people here would use inkscape as well though.

**Comment by FabioPiccinini** [comment]
I agree, the solution I proposed makes the comment more difficult to read.
If it were possible to replace the ; with - or , it would be more readable.

**Comment by aothms** [comment]
Thanks!

**Comment by FabioPiccinini** [comment]
Glad to help! I am happy to have made my first contribution, even if it's only a comma 😄

**Pull request merged**
