### PR TITLE
UI drawing improvements

### LINKED ISSUE #5651: Improvements to the Sheets and Drawings panes [Enhancement]
As mentioned [here](https://community.osarch.org/discussion/2562/is-it-ok-to-ab-use-sub-storeys-to-show-hide-elements#Comment_22555) I see a few areas where consistency, and ease of use could be improved. I've created this mockup for discussion, although I have edited my local files to make a number of these changes already, and it already feels better :-)
confusingicons
The goal is to:
1. Eliminate inconsistencies
Button position and order consistent between Sheets and drawings, divided into logical blocks
Use duplicate icon as used elsewhere
Double click in the Drawings list edits the title. Double clicking in the Sheets list does nothing. These should be aligned.
2. Use distinct icons that more clearly imply what they do
Eliminate using the same icon for different actions, and using different icons for essentially the same action
I switched the DXF icon to the outline drawing as whenever I remember seeing someone open DXF in AutoCAD it always looks outline-y to me.
3. Improve the usability (yeah, somewhat subjective)
Tuck the delete and uncommon stuff off to the left (I really didn't like the delete button next to the create sheet button.)
The blocks on the right work from left-to-right - Misc, Edit, Output, and are split using spacers.
4. Add quality-of-life improvements
On my system creating the drawings creates windows popping up and stealing focus, and are a pain to continuously shut down. This was especially true with my PDF viewer that was creating a new taskbar icon for each drawing. So I aim to make creating drawings and viewing drawings a separate button.
Also, adding selection checks to the Sheets list, and Shift-click on the Create Sheet button to create multiple sheets

Hopefully the picture is worth a thousand words too.

I can _probably_ do all of this myself, but I'd like to see if anyone has objections or prefers the way it currently works, or better suggestions.

### PR DESCRIPTION
**Pull request by sboddy**
As mocked up and discussed in #5651 this is the result. Results in:
image

### CODE REVIEW

**Comment by theoryshaw** [comment]
This seems good to me. 

My only comment, upon running `bim.create_sheets()` or  `bpy.ops.bim.create_drawing()` it would be nice if the drawing/sheet opened up in the default svg viewer, as before--currently it just runs behind the scenes.

**Comment by sboddy** [comment]
Yeah. It occured to me after the fact that maybe when doing a none-shifted click, it would be OK to still open the file. I was mostly focused on not having Shift-click firing up windows like a gatling gun on meth. That's an easy fix. I'll post a patch shortly.

**Comment by theoryshaw** [comment]
cool.. my only last comment would that even if you use shift +  `bim.create_sheets()` or shift + `bpy.ops.bim.create_drawing()` to bulk run the drawings/sheets, that it would still open the default viewer too, after each drawing/sheet is created. 

I use this as a time to review the drawings, as they run and open.

**Comment by sboddy** [comment]
Hmmm. I specifically wrote this to _stop_ this behaviour. On the Linux GNOME desktop this causes a focus stealing mess. I can't look at another window, and it pops up constantly on the monitor where my mouse is, stealing focus and hiding other windows. Move to the other monitor and it pops up there too, making it impossible to do _anything_ till the whole run ends. Now if they all opened up in < 1s, this would not be so bad, but even with my simple model it takes long enough to "p" me off. It's worse if using the sheet pdf convert command, because each windows appears separately in the task bar, so I can't right-click -> quit 12 windows. I have to close each of them down individually.

I'll have a think. Maybe there's a way of making it choose-able. Or maybe add another modifier. Hmmm. Maybe the Window (Super) key could be added as a modifier to open the windows? Would that work?

**Comment by theoryshaw** [comment]
Fair enough, that makes sense. A preference would be nice, but defer to you. 
I defer to @Andrej730 or other core developers to make the final merge decision.

**Comment by sboddy** [comment]
OK, So I have it working where adding Ctrl to the click will optionally open the files as they are generated as per the original behaviour. The Super key was a non-starter, as it doesn't look like that is tracked in Blender events. I'll push the change. Anyone else can weigh in on which behaviour should be default - easy enough to swap. Will push in a minute or two.

**Comment by Andrej730** [comment]
Please run black formatter on this PR. If you have `black` installed, you can just run it with `black .` from the repository folder.

**Comment by sboddy** [comment]
> Please run black formatter on this PR. If you have `black` installed, you can just run it with `black .` from the repository folder.

Hmmm. It is tweaking a lot of things I never touched at all. Is that OK? Is it just that this code hasn't been blacked since you started enforcing its use?

**Comment by Andrej730** [comment]
> Hmmm. It is tweaking a lot of things I never touched at all. Is that OK? Is it just that this code hasn't been blacked since you started enforcing its use?

Some not formatted code sneaks here and there. You can skip the parts of codebase unrelated to this PR, doesn't really matter.

**Comment by sboddy** [comment]
Never been a huge fan of auto-formatting. I sometimes lay something out for clarity, so to have it then smushed up in a form that is harder to read... sigh. Well your house, your rules.

Is there a page describing how to apply black to submissions? If I run it at the git root I get a different result to running it in the subfolder because there are multiple pyproject.toml files scattered through the tree, and they are not aligned.
I _think_ you want me to run it in the root with _that_ pyproject.toml and cherry pick files to stage, as that gives fewer diff lines. If I run it in the folder it is defaulting to code-line width of 80, and I get a **lot** of reformatting crap.

**Comment by Andrej730** [comment]
> Never been a huge fan of auto-formatting. I sometimes lay something out for clarity, so to have it then smushed up in a form that is harder to read... sigh. Well your house, your rules.

You can use `# fmt: off` for some big blocks but sometimes it's a just sign that too many things are nested and it affects code readibility.

> Is there a page describing how to apply black to submissions? If I run it at the git root I get a different result to running it in the subfolder because there are multiple pyproject.toml files scattered through the tree, and they are not aligned.
> I _think_ you want me to run it in the root with _that_ pyproject.toml and cherry pick files to stage, as that gives fewer diff lines. If I run it in the folder it is defaulting to code-line width of 80, and I get a **lot** of reformatting crap.

black format for the entire repo described `pyproject.toml` in the repo folder, so it should applied from the root folder.

**Comment by sboddy** [comment]
Ugh. It looks like my version of black (21.12b0) that comes with Ubuntu 22.04 LTS is doing things differently to the one in the ci job (24.10). I'll look into it.

**Comment by sboddy** [comment]
OK, so that is now done with the exact same version. It is _probably_ still going to fail the job because of an extraneous line in a file which my patch does not even touch. I have no idea why it is picking just that one up, and not all the other non-conformant files. Do I "fix" unrelated files? Or can you push a button somewhere to say "go ahead anyway"?

**Comment by Andrej730** [comment]
> Do I "fix" unrelated files? Or can you push a button somewhere to say "go ahead anyway"?

Doesn't really matter, it's okay to leave them unformatted. They're probably already formatted on the main branch.

Can you please fix this one?
image

**Comment by sboddy** [comment]
Erm. Hang on. This might be an error changing that I just did it and pushed thinking this was like for like. Now I test it, the disabling of icons is not happening when the highlight is not on an actual drawing, i.e. one of the category folders. Let me revert and check what is going on here.

**Comment by sboddy** [comment]
OK. Now it is good to go.

**Comment by Andrej730** [comment]
Thanks for the contribution!

**Pull request merged**
