### PR TITLE
Windows & Visual Studio build scripts continued

### PR DESCRIPTION
**Pull request by Stinkfist0**
I will be pushing some enhancements and fixes to this PR during the weekend.

### CODE REVIEW

**Comment by Stinkfist0** [comment]
I'd have one more commit pending at my home PC, but it seems that the SSD broke or something and I cannot currently boot my PC... I'll probably re-do the commit at work.

**Comment by aothms** [comment]
Sorry to hear that. Btw. I started using boost::to_upper(_copy) and its -lower equivalent. For the sake of consistency maybe that's better sake then your std::transform(). But anyway everything better than this for-loop from hell.

**Comment by Stinkfist0** [comment]
Yup, actually I even added `// TODO add toLower() and toUpper() string helper functions for the project` there in the commit.

**Comment by Stinkfist0** [comment]
OK, the stuff I have in mind for now is in. I left couple warnings as I wasn't 100 % sure if these should be simply suppressed or not, so maybe you can check these out when you have the time.:
```
src\ifcparse\IfcHierarchyHelper.cpp(248): warning C4100: 'context': unreferenced formal parameter
src\ifcparse\IfcHierarchyHelper.cpp(247): warning C4100: 'place': unreferenced formal parameter
src\ifcparse\IfcHierarchyHelper.cpp(293): warning C4127: conditional expression is constant
src\ifcparse\IfcHierarchyHelper.cpp(315): warning C4100: 'context': unreferenced formal parameter
src\ifcconvert\ColladaSerializer.cpp(54): warning C4100: 'default_material_name': unreferenced formal parameter
```

**Comment by Stinkfist0** [comment]
I should be done with this for now, if you don't have any issues with the commits. Next I'll try to focus on actual IfcOpenShell/IfcConvert enhancements. :)

**Comment by Stinkfist0** [comment]
I'll probably also commit logic for detecting the used Visual Studio version automatically in vs-cfg.cmd by Monday.

**Comment by aothms** [comment]
Ok, thanks for the update. Looking forward for that, take your time.

**Comment by Stinkfist0** [comment]
@aothms OK, ready to rock!

**Comment by aothms** [comment]
Great. Thanks again for a great effort. I don't really have the time to test extensively, but since changes in this PR have already proven to help users [1] I'm just going ahead and merge it.

[1] https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/d6365537/?limit=25&page=2#59c9

**Pull request merged**
