### PR TITLE
BlenderBIM: (Docs) Test animation on how to open an IFC file + OpeningElement Flowchart

### PR DESCRIPTION
**Pull request by garylzimmer**

### CODE REVIEW

**Comment by garylzimmer** [comment]
Just going to be doing a few quick screen recordings with some simple common tasks in BlenderBIM so people don't have to refer back to youtube videos

**Comment by garylzimmer** [comment]
Regarding the flowchart, TBH, I have no idea what this means, where it should go, or how to incorporate it into the docs...I'm just trying to be helpful and save people the trip to twitter!

**Comment by garylzimmer** [comment]
Is webm acceptable? I made a gif export as well, but the file size was huge in comparison.

**Comment by luzpaz** [comment]
any traction on this?

**Comment by Moult** [comment]
I think this is superseded by https://blenderbim.org/docs/users/exploring_an_ifc_model.html

The image needs to be documented sometime though, but that's already mentioned in another bug.

**Pull request closed without merging**
