### PR TITLE
Openings should be either polygonal or extrusion based

### PR DESCRIPTION
**Pull request by Gorgious56**
Following the task in the project board, I've added a dropdown in the tool interface to select which type of void the user wants to apply.

Here's a short video explaing the workflow

capture

It seems all types works except for `IfcExtrudedAreaSolid/IfcMaterialProfileSetUsage` which throws an error. 

```
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\site-packages\ifcopenshell\api\geometry\add_representation.py", line 69, in execute
    return self.create_model_representation()
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\site-packages\ifcopenshell\api\geometry\add_representation.py", line 122, in create_model_representation
    return self.create_variable_representation()
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\site-packages\ifcopenshell\api\geometry\add_representation.py", line 239, in create_variable_representation
    return self.create_material_profile_set_extrusion_representation()
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\site-packages\ifcopenshell\api\geometry\add_representation.py", line 523, in create_material_profile_set_extrusion_representation
    profile_set = self.settings["profile_set_usage"].ForProfileSet
AttributeError: 'NoneType' object has no attribute 'ForProfileSet'
```

I don't really know how to test if everything is in order in the ifc file in the end though.

### CODE REVIEW

**Comment by Gorgious56** [comment]
I guess the next step is to ask the user for the type before clicking on "Add Void" and instead of adding a cube, adding the relevant representation ? ie a cylinder for circle extrusion, etc ?

**Comment by Moult** [comment]
Indeed it will never work for "IfcExtrudedAreaSolid/IfcMaterialProfileSetUsage" because that is a parametric type based profile, and openings don't have types, so all good :)

> I guess the next step is to ask the user for the type before clicking on "Add Void" and instead of adding a cube, adding the relevant representation ? ie a cylinder for circle extrusion, etc ?

Yep :) Extrusions are always in the +Z, so that's the convention that needs to be followed.

**Comment by Gorgious56** [comment]
Quick update 
capture
capture

And a messy torus void: 
image

Test in BIMvision
image



@Moult I was thinking about the best way to implement this. Should profiles be tied to the new Profile editor you created so that the user can select an existing profile in a list ? for now I just added hardcoded profile parameters but I'm sure it can be tied more tightly with existing systems. I also don't really know how to handle arbitrary extrusions and text literals ?

**Comment by Moult** [comment]
> Should profiles be tied to the new Profile editor you created

Nah, managed profiles are necessary for standardised type-based modeling, like structural steel, mullion, skirting, molding, curtain wall transoms, etc. Openings / penetrations and booleans are the one thing that don't need any managed profiles.

Openings are almost, almost always a rectangle or cylinder, nothing else ... because that's what you can build. Booleans are either those simple shapes, or flat polyline planes that are bespoke to an area. Anything more complex is an arbitrary mesh because an architect is being creative.

> how to handle arbitrary extrusions and text literals

An arbitrary extrusion is just a mesh. The user can edit it using ops.bim.enable_editing_extrusion_profile and ops.bim.edit_extrusion_profile I suspect. A text literal is... unrelated to openings and shouldn't be supported I guess?

**Pull request closed without merging**
