### PR TITLE
[IfcConvert] Added tasks in the xml export

### PR DESCRIPTION
**Pull request by christt105**
The XML export contains a new tag "tasks" that contains all the tasks in a hierarchy tree. Each task contains its definition, its task time and the linked tasks (predecessor and successor). I think that this solves #2062.

### CODE REVIEW

**Comment by Moult** [comment]
At a glance, I notice this doesn't start from an IfcWorkSchedule. Might I recommend starting the task traversal from there? The work schedule groups tasks and separates between baselines, FM tasks, etc. Typically in a 4D workflow unless it's a single snapshot timeline, you'd have multiple schedules.

**Comment by aothms** [comment]
Many thanks @christt105 

@Moult do you have a file with workschedule and tasks ready? Then I run it through the code and see if the output matches your ideas.

**Comment by Moult** [comment]
Here are two example files. First is a minimal example - two workschedules, each having 2 rooted tasks, and one subtask (so 3 tasks per schedule). No other data.

[example-4d-minimal.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8384473/example-4d-minimal.txt)

The second is an import from P6 via the Ifc4d util so it's got quite a bit of data to play with. It has sequences, sequence types, lagtimes, calendars, calendar inheritance, times, resources, and I also put in a single wall and assigned it as as construction output, and assigned a resource too.

[example-4d.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8384474/example-4d.txt)

Have fun and all the best!

**Comment by aothms** [comment]
Thanks both.

One point of improvement I'd see is that the relationship from task to property / quantity is not made. This is apparent in example-4d. There are a bunch of IfcElementQuantities in there. @christt105 can you include this bit in your handling of tasks https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/schema_dependent/XmlSerializer.cpp#L304-L315 ?

Other comment is whether we should sort nodes wrt to `IsSuccessorFrom` `IsPredecessorTo`, but I guess it doesn't add much.

**Comment by aothms** [comment]
Edit: for reference. XML output:

~~~xml
<tasks>
		<IfcWorkSchedule id="01kg$ivNv3fBmoohLpSM40" Name="a" CreationDate="2022-03-31T09:04:00.358456" StartTime="2022-03-31T09:04:00.357578" PredefinedType="NOTDEFINED">
			<IfcTask id="1pn51cNAXCH9eVKJhUSOOP" Name="a" Identification="a.1" IsMilestone="false" PredefinedType="NOTDEFINED"/>
			<IfcTask id="1xoBkVt9H3butPK$sRP6rd" Name="c" Identification="a.2" IsMilestone="false" PredefinedType="NOTDEFINED">
				<IfcTask id="0MlptHd8PDO8XMQg3di4u6" Name="b" Identification="a.2.1" IsMilestone="false" PredefinedType="NOTDEFINED"/>
			</IfcTask>
		</IfcWorkSchedule>
		<IfcWorkSchedule id="3TwmJ8gOvDmguQk$yyyRgi" Name="b" CreationDate="2022-03-31T09:04:01.147251" StartTime="2022-03-31T09:04:01.146393" PredefinedType="NOTDEFINED">
			<IfcTask id="2d5zar5_5Agf0VP8MjvNMk" Name="c" Identification="b.2" IsMilestone="false" PredefinedType="NOTDEFINED">
				<IfcTask id="3ByMxy3q99muvcXvZ2It7P" Name="b" Identification="b.2.1" IsMilestone="false" PredefinedType="NOTDEFINED"/>
			</IfcTask>
			<IfcTask id="0$WtrjzMX5hhnjpv12ihCq" Name="a" Identification="b.1" IsMilestone="false" PredefinedType="NOTDEFINED"/>
		</IfcWorkSchedule>
	</tasks>
~~~

~~~xml
<quantities>
		<IfcElementQuantity id="03KMPSoGrDjPNhU5zcj8yz" Name="Qto_TaskBaseQuantities">
			<IfcQuantityTime Name="StandardWork" TimeValue="5"/>
		</IfcElementQuantity>
		<IfcElementQuantity id="2uLTQH4d95f9qUAWKaqYH0" Name="Qto_TaskBaseQuantities">
			<IfcQuantityTime Name="StandardWork" TimeValue="5"/>
		</IfcElementQuantity>
		...
	</quantities>
	<tasks>
		<IfcWorkSchedule id="3Ci5YJ34530ftO_Xqb$slF" Name="Revit Sample Project" CreationDate="2022-03-31T09:07:45.176743" StartTime="2022-03-31T09:07:45.176550" PredefinedType="NOTDEFINED">
			<IfcTask id="1xxIVeYJj1PgXMqSVob55H" Name="Revit Building" Identification="1" IsMilestone="false" PredefinedType="NOTDEFINED">
				<IfcTask id="2$iaDAlmz50AYYQP2CP0Wp" Name="ROOTED ACTIVITY" Identification="EC2650" Status="Not Started" IsMilestone="false" PredefinedType="CONSTRUCTION">
					<IfcTaskTime DurationType="WORKTIME" ScheduleDuration="P5D" ScheduleStart="2021-05-03T09:00:00" ScheduleFinish="2021-05-07T17:00:00" EarlyStart="2021-05-03T09:00:00" EarlyFinish="2021-05-07T17:00:00" LateStart="2021-10-19T09:00:00" LateFinish="2021-10-25T17:00:00" FreeFloat="P121D" TotalFloat="P121D" IsCritical="false"/>
				</IfcTask>
				<IfcTask id="3iq5RcR$z1ZfpFjRNdda2X" Name="Roof" Identification="1.2" IsMilestone="false" PredefinedType="NOTDEFINED">
					<IfcTask id="2D02YihqP7NOxJC8wAukUA" Name="Place Roof Trusses and Sheathing" Identification="EC1390" Status="Not Started" IsMilestone="false" PredefinedType="CONSTRUCTION">
						<IfcTaskTime DurationType="WORKTIME" ScheduleDuration="P5D" ScheduleStart="2021-08-09T09:00:00" ScheduleFinish="2021-08-13T17:00:00" EarlyStart="2021-08-09T09:00:00" EarlyFinish="2021-08-13T17:00:00" LateStart="2021-10-19T09:00:00" LateFinish="2021-10-25T17:00:00" FreeFloat="P51D" TotalFloat="P51D" IsCritical="false"/>
						<IsSuccessorFrom id="2RrA2gal19I9gWPTRqV$9y"/>
					</IfcTask>
					<IfcTask id="3cyM27bs52yBmngPgvxZ48" Name="Place Mechanical Equipment Supports" Identification="EC1400" Status="Not Started" IsMilestone="false" PredefinedType="CONSTRUCTION">
						<IfcTaskTime DurationType="WORKTIME" ScheduleDuration="P5D" ScheduleStart="2021-08-09T09:00:00" ScheduleFinish="2021-08-13T17:00:00" EarlyStart="2021-08-09T09:00:00" EarlyFinish="2021-08-13T17:00:00" LateStart="2021-08-09T09:00:00" LateFinish="2021-08-13T17:00:00" FreeFloat="P0D" TotalFloat="P0D" IsCritical="true"/>
						<IsSuccessorFrom id="2RrA2gal19I9gWPTRqV$9y"/>
						<IsPredecessorTo id="1OLiZQvXv6CelM8GmNvaYJ"/>
					</IfcTask>
					...
					~~~

**Comment by christt105** [comment]
The output with the property/quantity relationship is this:
```xml
<quantities>
	<IfcElementQuantity id="03KMPSoGrDjPNhU5zcj8yz" Name="Qto_TaskBaseQuantities">
		<IfcQuantityTime Name="StandardWork" TimeValue="5"/>
	</IfcElementQuantity>
        ...
</quantities>
<tasks>
		<IfcWorkSchedule id="3Ci5YJ34530ftO_Xqb$slF" Name="Revit Sample Project" CreationDate="2022-03-31T09:07:45.176743" StartTime="2022-03-31T09:07:45.176550" PredefinedType="NOTDEFINED">
			<IfcTask id="1xxIVeYJj1PgXMqSVob55H" Name="Revit Building" Identification="1" IsMilestone="false" PredefinedType="NOTDEFINED">
				<IfcTask id="2$iaDAlmz50AYYQP2CP0Wp" Name="ROOTED ACTIVITY" Identification="EC2650" Status="Not Started" IsMilestone="false" PredefinedType="CONSTRUCTION">
					<IfcTaskTime DurationType="WORKTIME" ScheduleDuration="P5D" ScheduleStart="2021-05-03T09:00:00" ScheduleFinish="2021-05-07T17:00:00" EarlyStart="2021-05-03T09:00:00" EarlyFinish="2021-05-07T17:00:00" LateStart="2021-10-19T09:00:00" LateFinish="2021-10-25T17:00:00" FreeFloat="P121D" TotalFloat="P121D" IsCritical="false"/>
					<IfcElementQuantity xlink:href="#03KMPSoGrDjPNhU5zcj8yz"/>
				</IfcTask>
                                        ...
					~~~

**Comment by Moult** [comment]
> Other comment is whether we should sort nodes wrt to IsSuccessorFrom IsPredecessorTo, but I guess it doesn't add much.

> PD: The sort nodes should not be better to do it from the "SchedulingStart" attribute? I am just asking, I don't have experience with Ifc.

No need to sort nodes. Scheduling software are dynamically sorted by all sorts of user specified criteria and the critical path analysis is always recalculated anyway.

> I don't know what are IfcResources, but maybe will be good to add it to the XML export.

Resources are typically labour, equipment, or material consumed in the task. For example, pouring concrete may use a material resource of concrete, and a labour resource of a formworker, and an equipment resource of a concrete pump. These have productivity rates and cost rates, and can calculate things like resource utilisation. It's probably not necessary for a first pass of this feature.

> The task with the name "Ground Floor Walls" and id 1CpPHOBOrElOGpr0ohPtE4, has a cube as an output, but I cannot find where it is to export. I use the IfcTask::OperatesOn(), but it seems that does not contains the object. Any clue?

Here are the relationships that relate the task to the cube wall. You'd want to investigate the HasAssignments relationship. Note that there are two ways products can be associated. By far the most common (which is shown in the sample) is as an "output" of the task. However, some products (like sacrificial formwork) may also be used as an input of the task.

```
#502=IFCTASK('1CpPHOBOrElOGpr0ohPtE4',$,'Ground Floor Walls',$,$,'EC2500',$,'Not Started',$,.F.,$,#503,.CONSTRUCTION.);
#637=IFCRELASSIGNSTOPRODUCT('0KzU1ul3n6DBynhp32Qbel',$,$,$,(#502),$,#612);
#612=IFCWALL('0n0tLYgcrDlQnOk$9I_KgF',$,'Cube',$,$,#636,#630,$,.ELEMENTEDWALL.);
```

image

Hope it helps.

**Comment by christt105** [comment]
Great, thank you so much for the info!

**Comment by aothms** [comment]
> I had to get the IfcWorkPlan::IsDecomposedBy() as auto, which may be wrong with the coding rules of the project, but in the Ifc2x3 it is of type IfcRelDecomposes

I think that's perfect use of `auto`.

Thanks a lot for all the refinements, I'll wait a bit too see if some feedback comes from @Moult otherwise I'm very happy to merge this.

**Pull request merged**
