### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by klacol**

### CODE REVIEW

**Comment by aothms** [comment]
Dear Klaus, can I ask why you closed the pull request? In case you want to resubmit it, can I suggest to squash the commits into a single commit? Thanks for your effort, would happily incorporate your changes.

**Comment by klacol** [comment]
Hi Thomas, since I am new to these things in GitHub I made a mistake. I wanted to include the changes in your master to my fork and made something wrong, so that I unintentionally created a pull request for your master. I will check how to do that and test then my fork first. Then, if everything is ok in my fork, I will send you the pull request again.

**Comment by aothms** [comment]
Ok, thanks for clarifying. Sounds like a great plan. Indeed, github can be confusing.

**Comment by Stinkfist0** [comment]
@klacol It's best to work on your new features in a feature branch, not in master, this will make merging or preferably(?) rebasing (cleaner history) a lot easier and hassle-free.

**Comment by klacol** [comment]
@Stinkfist0  Thanks, I will try that

**Pull request closed without merging**
