### PR TITLE
Upon removal, empty aggregates prioritise null if possible.

### PR DESCRIPTION
**Pull request by Moult**
See #1766.

### CODE REVIEW

**Comment by aothms** [comment]
I see you don't check whether the lower bound of the list is indeed 1. I guess there could also be `OPTIONAL LIST [0:?]` (although the semantic differences is unclear)? Also it's only for aggregates of instances, not of other datatypes.

I'll add a note about these things, but let's not delay merging the PR. Checking the lower bound is a bit difficult because the attribute is not necessarily directly an aggregate. It can also be a named type for example IfcCompoundPlaneAngleMeasure or SELECT with IfcPropertySetDefinitionSet or something else equally crazy.

A complicating factor is that the attribute types on the C++ side are just enumerations. Ideally instead of Argument_AGGREGATE_OF_AGGREGATE_OF_ENTITY_INSTANCE we whould have some sort of class definition AGGREGATE(AGGREGATE(ENTITY_INSTANCE)) so that we could apply this logic more generally.

**Comment by aothms** [comment]
> Also it's only for aggregates of instances, not of other datatypes.

Duh, this is the file.remove() function, that doesn't apply to other datatypes.

**Comment by Moult** [comment]
Cheers :) yes I regard null and empty list to be semantically equivalent so I didn't bother checking the lower bound.

Agree about the third paragraph, but I didn't understand your second paragraph? How does select affect this code?

**Comment by aothms** [comment]
> How does select affect this code?

Only if you want to check the lower bound. The aggregate type definition can be quite a few indirections away. Through various named type definitions or selects (actually maybe not selects, maybe there would be another entity instance always in between then). It's not important.

**Comment by aothms** [comment]
> semantically equivalent

Maybe also something we can take another look at for 4.3. Although I can't really judge how important this is. You also see this with booleans for example. Where you have (a) `optional boolean` (b) `logical` and even (c) `optional logical`. (a) and (b) are I'd say equivalent unless you want to debate the semantic difference between "omitted" and "unknown". (c) I'm really not sure why one would need 4-state booleans.

**Pull request merged**
