### PR TITLE
Minor fixes to BlenderBIM's IFC importer

### PR DESCRIPTION
**Pull request by yorikvanhavre**
* Allow IfcAnnotations which have no related IfcGroup
* Added a couple of IfcAnnotation.ObjectType types exported by FreeCAD

### CODE REVIEW

**Comment by Moult** [comment]
```
            if group: # annotations could exist that are not in an IfcGroup
```

Is this change hunk required? I don't see the purpose of it. Have you got a file to test where it is needed?

The `place_object_in_spatial_decomposition_collection` function decides where to place an object in the Blender collection tree. If it's an annotation in a drawing, then I place it in a particular Blender collection. Otherwise, it follows the rules of all other IFC elements (e.g. follows the spatial hierarchy or whatever).

**Comment by yorikvanhavre** [comment]
This file doesn't open with the current code: https://gitlab.com/openingdesign/101_W_33rd_St/-/blob/main/Models%20and%20CAD/IFC/101_W_33rd_St_Details_D.ifc it fails because the "group" list is empty

**Comment by theoryshaw** [comment]
Thanks @yorikvanhavre 
exact file version here: https://gitlab.com/openingdesign/101_W_33rd_St/-/blob/1288e92f34e5c6dd9e38a229a012b5488d90f327/Models%20and%20CAD/IFC/101_W_33rd_St_Details_D.ifc

**Comment by Moult** [comment]
I tested with the file and it works without that hunk. Are you sure that file demonstrates an issue?

**Comment by Moult** [comment]
Bump @yorikvanhavre :)

**Comment by yorikvanhavre** [comment]
Indeed everything seems working now... weird! Anyway, the best bugs are the bugs that fix themselves :)

**Pull request closed without merging**
