### PR TITLE
Attempt at implementing root.create_entity

### PR DESCRIPTION
**Pull request by kaiaurelienzhu**
Hi Dion,

- Added doc strings for root.create_entity API. I tried to follow the format in project.create_file
- Removed the try except in the api node for debugging purposes.

I'm getting a Key error in the extract_docs function when I try and implement the API node on the root.create_entity

Ran out of time but will get onto it again next week.

### CODE REVIEW

**Comment by Moult** [comment]
You need to remove `**settings: dict` and turn the arguments into actual keyword arguments like https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/project/create_file.py#L6 as an example.

**Comment by kaiaurelienzhu** [comment]
Hi @Moult, 

I've synced up my git repo ifcopenshell with Blender now and changes made to my local IfcOpenShell python api code seems to be working now. I added some print statements in the init.extract_docs functions to test. 

I've removed the **settings dict for root.create_entity on my local but still seem to be getting a KeyError. I did notice though that there is ModuleNotFoundError coming from ifcopenshell, however when I tested with the ifc sverchok API node for project.create_file that it worked fine. Screenshot of error below.

image

**Comment by Moult** [comment]
The primary error is that it cannot load ifcopenshell. This may be due to incorrect initialisation of the BlenderBIM Add-on. Check all paths are symlinked correctly, and especially double check the `__init__.py` files at the top level of the add-on and the `bim/` folder. They have recently been updated. Make sure the BlenderBIM Add-on is enabled and you can import it using the Python console in Blender.

**Comment by kaiaurelienzhu** [comment]
Thanks Dion, all working now. I reviewed the bleeding edge documentation
and noticed a missing backslash in some of my mklink lines. I have my
branch of ifcopenshell api pushing to Blender now! Next week, I'll try and
get the root.create_entity working on my local and will send a PR.

Been a slow start as I've been struggling to find time to study due to the
registration interview but it will be over soon and I will be able to
contribute more to this project.

**Comment by Moult** [comment]
How's it going @kaiaurelienzhu ? Anything I can help with?

**Comment by Moult** [comment]
I've just changed the base from v0.6.0 to v0.7.0 otherwise this PR becomes a bit unreadable :)

**Comment by Moult** [comment]
Bump :)

**Comment by kaiaurelienzhu** [comment]
Hi Dion,

Apologies, I haven't really gone much further than this. To be frank, I
realised I needed to improve my knowledge of IFC itself, blender and
sverchok A LOT before I could really be useful...

At the moment I am focusing on ISO19650 and IFC before diving into Blender.
It's been tough trying to find use cases at work but I am steadily getting
there.

At this stage, this is on pause for me, but I would be happy to take it up
either under direction from you or get started again once I've gained
enough knowledge to be able to lead it properly.

Let me know what you think,

**Comment by aothms** [comment]
Imho doing is the quickest way of learning. We're here to help you get unstuck on the many details regarding IFC, Python and the various APIs. Best of luck, Thomas.

**Comment by Moult** [comment]
Hey @kaiaurelienzhu did you know @mdjska is working on this as part of GSoC this year? It would be a great time to collaborate with her if you were keen on taking another stab at this :)

**Comment by kaiaurelienzhu** [comment]
Hey Dion,

Yes I was aware and have been following closely. Unfortunately, due to my
current capacity and circumstances (I am in the middle of an international
move), I am unable to help out for the year. I am disappointed about that
as this was a perfect opportunity for me to contribute...

However, I am pleased to say I have completed my ISO19650 training and
continue to deepen my knowledge in IFC. Soon, Blender will be on the cards.
I am expecting to have enough knowledge to be useful hopefully by mid 2023.

I will be in touch,

**Comment by Moult** [comment]
Closing as from the work from @mdjska this is now implemented :)

**Pull request closed without merging**
