### PR TITLE
build-deps.cmd: fix boost build configuration for VS 2015. Fixes #279…

### LINKED ISSUE #279: cmake problems with current master
I tried to compile the current master at f64246f7c5a71fc7942445957101ca43c2c4d952 on Windows 10, 64 bit, with Visual Studio 2015 or 2017, but both failed at the `run-cmake.bat` step. I have cmake version 3.9.2 installed. 

The error message when using VS 2105 is this:
[vs2015.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1409996/vs2015.txt)
and here is the CMakeError.log
[CMakeError.log](https://github.com/IfcOpenShell/IfcOpenShell/files/1410000/CMakeError.log)
As I understand it, there is a problem related to pthread.h

When using VS 2017, I get the following error:
[vs2017.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1410005/vs2017.txt)
Saying the bitness does not match!?

Any ideas or comments?

### PR DESCRIPTION
**Pull request by Stinkfist0**
…. [ci skip]

### CODE REVIEW

**Comment by aothms** [comment]
Thanks! I didn't follow the discussion to great extent. It seems this fix also affects msvc 2015 users then. Is that intentional?

**Comment by Stinkfist0** [comment]
This fix should affect VS versions older than  2017.

**Comment by thorade** [comment]
I just started compilation with VS2017, afterwards I will compile with VS2015.
So, in about 2-3 hours I can tell you whether it fixes the problem I was having.

**Comment by Stinkfist0** [comment]
oops, forgot one debug echo there, will remove

**Comment by thorade** [comment]
I started over to also test the new commit, now I am getting the following error on VS2017
```
Building Boost build script.
Building Boost.Build engine
cl : Befehlszeile warning D9035 : Die Option "GZ" ist veraltet und wird in einer der nächsten Versionen entfernt.
cl : Befehlszeile warning D9036 : "RTC1" anstelle von "GZ" verwenden
cl : Befehlszeile warning D9002 : Unbekannte Option "/MLd" wird ignoriert.

Bootstrapping is done. To build, run:

    .\b2

To adjust configuration, edit 'project-config.jam'.
Further information:

    - Command line help:
    .\b2 --help

    - Getting started guide:
    http://boost.org/more/getting_started/windows.html

    - Boost.Build documentation:
    http://www.boost.org/build/doc/html/index.html
Building Boost 1.65.1 --with-system --with-regex --with-thread --with-program_options --with-date_time --with-iostreams --with-filesystem Please be patient this will take a while.
notice: could not find main target call
notice: assuming it is a name of file to create.
notice: could not find main target .\b2
notice: assuming it is a name of file to create.
Performing configuration checks

    - 32-bit                   : yes
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : yes
    - symlinks supported       : no
    - junctions supported      : yes
    - hardlinks supported      : yes
    - zlib                     : no
    - bzip2                    : no
    - lzma                     : no
    - has_icu builds           : no
don't know how to make <e>call
don't know how to make <e>.\b2
...found 2 targets...
...can't find 2 targets...

An error occurred

Build ended at 12:46:11,19. Time elapsed 0:09:15.95.
```

**Comment by thorade** [comment]
Sorry, my mistake, I had to resolve a merge conflict due to the force push, and I did that wrong.

**Comment by thorade** [comment]
Works for me, with vs2017-x64 and vs2015-x64

**Comment by aothms** [comment]
Wonderful. Thanks.

**Pull request merged**
