### PR TITLE
Check shell validity before passing it over to TOPODB::Shell()

### PR DESCRIPTION
**Pull request by Stinkfist0**
A shell validity check that was found to be useful earlier this year.

### CODE REVIEW

**Comment by aothms** [comment]
Thanks. Out of curiosity, do you have a test file you can share (also privately at models@ifcopenshell.org) where this helped?

**Comment by Stinkfist0** [comment]
I'll contact there original author of this code if he can remember some specific file that he had problems with.

**Comment by Stinkfist0** [comment]
Unfortunately we could not remember the specific test files. No bad feelings if this is rejected, can be easily resubmitted if we find the actual problematic files.

**Comment by aothms** [comment]
Yeah I think I have to let this one slip. There's been too many changes in the whole TopoDS_Shell handling in the 0.6 branch for this to make sense. Thanks anyway,

**Pull request closed without merging**
