### PR TITLE
Improve UI for multi input string fields

### PR DESCRIPTION
**Pull request by Gorgious56**
Following https://github.com/IfcOpenShell/IfcOpenShell/issues/1609
This PR aims to improve UX when using multi-input fields such as Middle Names and Organisation telephone number.
Added a + operator to add an item to the current multi-input field. If there is only one left, the user can't delete it. If there are more than one, a cross appears on the field's right to delete it.

BES_28

Possible improvements :
I'd very much like some feedback on possible UX/UI/Code improvements
Limit the number of possible items per CollectionProperty
Limit the number of character per field
Force using alphanumeric characters
Force using numeric characters on telephone number

### CODE REVIEW

**Comment by Gorgious56** [comment]
Trying out a more compact UI
BES_31

**Comment by Gorgious56** [comment]
Maybe even simpler, without using box layouts
image

**Comment by Gorgious56** [comment]
Using minus icon instead of cross to remove unwanted elements :
image

**Comment by Gorgious56** [comment]
Bringing inputs belonging to the name property closer together using a `column` layout

**Comment by MarcelP102** [comment]
Nice eye for detail!

**Comment by Moult** [comment]
Looks great!

**Pull request merged**
