### PR TITLE
Update operator.py (IFC to CSV Export)

### PR DESCRIPTION
**Pull request by c4rlosdias**
missing output file format in arguments

### CODE REVIEW

**Comment by Moult** [comment]
Thank you!

**Comment by Moult** [comment]
Would you be interested in helping write extra format support?

**Comment by c4rlosdias** [comment]
yes of course.  xlsx and ods, right? perhaps the export button should have something like "export" instead of "export csv".

**Comment by Moult** [comment]
Indeed, it would be nice to have a dropdown to select either CSV, XLSX, or ODS, then depending on the format it might show extra options (e.g. delimiter for CSV), then the export button will use whatever format you choose.

For now import only works with CSV.

**Comment by c4rlosdias** [comment]
ok I will work on it

**Pull request merged**
