### PR TITLE
ifcopenshell python element utils, add get layer method

### PR DESCRIPTION
**Pull request by berndhahnebach**
This is what I have been using in the company in BIMTester and what we use in FreeCAD on import of IFC to get the layer of a element.

bernd

### CODE REVIEW

**Comment by Moult** [comment]
I don't think this'll work with type representations nor mapped representations. Can I instead recommend using a traverse and check for layer assignment on shape representation? (I'm happy to deliberately forego representation item since that can be super expensive).

**Comment by berndhahnebach** [comment]
> 
> ... Can I instead recommend using a traverse and check for layer assignment on shape representation? ... 

How would this work?

**Comment by aothms** [comment]
Here it is in C++. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/Kernel.cpp#L264

>forego representation item 

With the new handling of inverses it shouldn't be as slow as in 0.6

**Comment by berndhahnebach** [comment]
What could I do to get this or some better code to directly get the layer get merged?

cheers bernd

**Comment by Moult** [comment]
Should be resolved now :) Hope it makes sense @berndhahnebach !

**Pull request closed without merging**
