### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by aothms** [comment]
Thanks. Could you revert changes to the following files as these are data files coming from official sources?

~~~
 .../bim/schema/enum_descriptions.json         |   2 +-
 .../ifcopenshell/express/DocAttribute.csv     | 522 ++++++++++++------
 .../util/schema/Pset_IFC4_ADD2.ifc            |  20 +-
~~~

**Comment by luzpaz** [comment]
Done in [fec15f3](https://github.com/IfcOpenShell/IfcOpenShell/pull/2366/commits/fec15f328c2f5da6c0b97432111f59d747855e64)

**Comment by luzpaz** [comment]
BTW, how do i submit BlenderBIM PRs ?

**Comment by aothms** [comment]
Thanks. BlenderBIM PRs are to be submitted here as well, just tag with [BlenderBIM] but I'm quite sure @Moult will read it untagged as well ;)

**Comment by luzpaz** [comment]
Do i need to checkout the blenderbim release tags?

**Comment by aothms** [comment]
No, they are just automatically tagged during the CD process, as far as I can tell they don't have any bearing on actual code.

**Pull request merged**
