### PR TITLE
Fetch pytest-blender dependencies

### PR DESCRIPTION
**Pull request by Gorgious56**
This aims to automatically retrieve `pytest-blender` dependencies

I'm pretty sure I put that in the wrong place so please correct me if I did a horrible thing :)

### CODE REVIEW

**Comment by Moult** [comment]
Close ;)

```
.PHONY: dev
dev:
	blender -p setup_pytest.py
```

**Comment by Gorgious56** [comment]
Ok the shroud around all of this is slowly dissipating ! Should be good now :)

Now that I think about it, I don't know if it's desirable to force update pip, maybe some users want to stick to a particular version ?
https://github.com/IfcOpenShell/IfcOpenShell/blob/dabb3b1cdeb3c75001060b421e2d06ea7d5eb11f/src/blenderbim/setup_pytest.py#L26

**Comment by Moult** [comment]
Your call :) Feel free to merge when you feel like it! Looks good here.

**Comment by Gorgious56** [comment]
OK I'll leave it for now and wait for an angry developer's feedback if something goes wrong ^^
Thanks for the pointers !

**Pull request merged**
