### PR TITLE
Duplicate aggregate

### LINKED ISSUE #3186: With aggregates, ifcopeningelements not showing in BB drawings.
We're using aggregates on [this](https://gitlab.com/openingdesign/highland_haven/-/blob/ed715b78194e319b79b778b1d30b4a4bd972766f/Models_and_CAD/Highland_Haven.ifc) project. 

As you can see from the following, the ifcopeningelement doesn't show in the drawing. 

Is there a relative easy way to correct this?

FLOOR PLAN - 1ST FLOOR

2023-05-22_19-13-38_Blender_blender

### PR DESCRIPTION
**Pull request by brunoperdigao**
This PR implements the idea presented in #3068 for duplication of aggregates. It also gives the possibility to refresh the copies if anything is changed in the original aggregates.

To duplicate, you have to select only the `IfcElementAssembly`. Right now, this operator is triggered by `crtl + shift + d`. It also works with sub-aggregates.

https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/ac112ab3-b30b-456d-af0a-9b0cb1f76e5d

After changing something in the original aggregate, select the `IfcElementAssembly`you want to refresh, press `F3` and type `refresh_aggregate`:

https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/356f8018-4126-4caa-bb3d-af4051955763

Also works with sub-aggregates copies that are detached:

https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/bff29454-6520-45d9-8607-34be2ca498d0

The current version might fix #3186 . There is still a problem with openings placement, but I think it's related to duplication in general (related to #3253 ). Nevertheless, this can be solved by refreshing the copy.

https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/a11c16bc-1061-4945-8cce-bb9c65174ec4

**Future improvements**
This PR is the basic implementation, and it's somewhat ready to use. I'm committed to work on the following improvements moving forward:
- Regarding the code, the operators are placed in the geometry module, because it was easier to start with the `OverrideDuplicate` as reference. Maybe this could evolve and go to the aggregate module.
- Create an ui for refresh operator, maybe here:
image

- Create an operator to refresh all instances
- Create an operator to select the base `IfcElementAssembly` of that group
- Create an operator to select the original instance of that aggregate
- Create an operator to unlink the aggregate from the original instance

### CODE REVIEW

**Comment by brunopostle** [comment]
Some comments:

I think there is a single 'parent' aggregate, and the 'children' are all duplicates of this. The children each have a epset indicating the guid of the parent, and the parent has an epset listing all the children. Is this right?

My experience of inkscape is that it has a similar parent/child system, and it it very hard to remember which is the parent since they all look the same. Sketchup components (for example) don't have this heirarchy, or at least it is hidden from the user - you can edit any component and they all behave as 'parent'.

Storing the relationship in two places requires that both entries are kept in sync, which could be fragile.

Could an IfcGroup be used to collect these duplicate aggregates? ie. all the sibling agregates can be found by checking if the current aggregate belongs to an IfcGroup and listing its children.

**Comment by brunopostle** [comment]
Maybe there is a 'make siblings the same as selected' operator. This would need to check all the siblings and only update them if they differ.

**Comment by brunoperdigao** [comment]
How would you suggest that I can check if they differ? I couldn't think of a way to do it and why I opted for a different approach

**Comment by brunopostle** [comment]
Checking would be hard as it needs to recurse, compare attributes, and check indirect stuff like materials and psets. Though however you do this tool, doing a minimal partial update would be preferable to discarding everything and recreating

**Comment by brunoperdigao** [comment]
So, here are my thoughts to move forward with this:
Create a simple "Duplicate Aggregate" that would not create a link between objects. Would work like a `shift+d` in Blender. I think this can be already useful in some cases and I can simplify the code in this PR in order to make it easier to be merged, so the syncing issues can be solved later.

The other operator would be "Duplicate Linked Aggregate". About this, I'm just thinking out loud, an option to simplify things and make it more efficient would be to restrict its use to work only if all the elements in the aggregate are types. That way, most of the syncing problems would be addressed. The "refresh" operator would just have to check the matrix for location and rotation, and other things like profile shapes for slabs, length and height for walls... Makes sense?

**Comment by brunopostle** [comment]
I think you have to try it and see, some types have representations, but others have profilesets or layersets and the representation is in the instance. But I think these are equivalent, a simple representation can be referenced in multiple instances, so your duplicate-linked operator doesn't need to copy any representations, it just copies the element and references the old representation, it can maybe do the same with placements, just use the original placement.

**Comment by theoryshaw** [comment]
Can this be pulled now? Is useful to me, in current state.

**Comment by Moult** [comment]
Thank you so much! Sorry for the delay in merging.

I am always a little hesitant to merge changes related to parts of the system that I don't have confidence in. I know for sure there are some aspects which I personally haven't tested much and are missing a ton of unit tests. Dealing with aggregates in practical scenarios is one of them. I hope I didn't make the wrong choice!

**Comment by theoryshaw** [comment]
Through use, we'll find them. :)

**Comment by brunoperdigao** [comment]
@Moult I understand. Can I help with testing? I'll take a look at the docs to see if I can understand how to do it

**Comment by Moult** [comment]
@brunoperdigao yes please! The first thing to do is make sure you can run tests: https://blenderbim.org/docs/devs/running_tests.html

The most important test for this type of things are BIM Tests (third bullet point on that page). Here are the existing basic aggregate tests: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/bim/feature/aggregate.feature

However your tests should be part of the geometry feature, see how we already have tests for duplicating various types of objects in different scenarios: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/bim/feature/geometry.feature#L282-L422 you should add tests related to duplicating aggregates.

The definition of those sentences are here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/bim/test_feature.py you will probably need to add some of your own e.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/bim/test_feature.py#L199-L202

**Pull request merged**
