### PR TITLE
fix: Rename the "MergeProject" recipe to "MergeProjects"

### PR DESCRIPTION
**Pull request by BlenderDefender**
This rename, alongside renaming "filepath" to "filepaths" and adjusting the docstring has been done to clarify, that this patch can be used to merge multiple IFC files into one (and not just two)

### CODE REVIEW

**Comment by Andrej730** [comment]
hi! can you please check the failing MergeProject tests?

https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/10432061829/job/28892393219?pr=5187

**Comment by BlenderDefender** [comment]
@Andrej730 Alright, should work now. I forgot to update the tests when renaming the patch recipe

**Comment by BlenderDefender** [comment]
Hmm... still failing 🤔

**Comment by Andrej730** [comment]
Hi! I'll merge it now to prevent the future merge conflicts.

**Comment by BlenderDefender** [comment]
Alright :+1: 
I've just tested it locally, the tests are passing:
image

**Pull request merged**
