### PR TITLE
BBIM tree names, make it possible to adjust layout

### PR DESCRIPTION
**Pull request by berndhahnebach**
https://community.osarch.org/discussion/comment/20038/#Comment_20038

duplicate of #4516 but I can not reopen it for some reason ...

### CODE REVIEW

**Comment by Andrej730** [comment]
Renaming objects should also be in sync with this - https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/handler.py/#L41-L42

**Comment by berndhahnebach** [comment]
I did not rename anything. I just created some method to be able to reaname all tree obj. at once.

This was not used at the code I changed. How would this be integrated ? 

Is this needed for the PR allready ?

**Comment by Andrej730** [comment]
> I did not rename anything. I just created some method to be able to adjust the layout of the tree object names at once.
> 
> This was not used at the code I changed. How would this be integrated ?
> 
> Is this needed for the PR allready ?

I think if we're moving object naming at import to a separate function in this PR then to keep it consistent we should also use the same function when user would try to rename object in outliner.

**Comment by berndhahnebach** [comment]
Do you have an example how to make use of this class to check names?

**Comment by berndhahnebach** [comment]
rebased on latest HEAD

How about an example to use the class for checking the names?

**Comment by Andrej730** [comment]
> How about an example to use the class for checking the names?

Check the handler function above, it gets triggered every time you change object's name. If we plan to allow different approach how objects named during import then we also need to make sure this approach is maintained when users will be renaming them later on.

**Comment by Moult** [comment]
We now use the loader function for names so closing.

**Pull request closed without merging**
