### PR TITLE
Improve filling operators and tests

### PR DESCRIPTION
**Pull request by Gorgious56**
The purpose of this PR is threefold :
- Prevent possible errors when certains combinations of operators and objects are not legal
- Write tests for add_filling and remove_filling operators
- Improve filling setup UX by displaying a list of all fillings of an opening :

image

Although I'm not sure this is the best way to retrieve an object from id :

https://github.com/Gorgious56/IfcOpenShell/blob/5ac533224e426c125e91089a9fa864b33215d853/src/blenderbim/blenderbim/bim/module/void/ui.py#L95

### CODE REVIEW

**Comment by Moult** [comment]
Are you sure all tests are covered in this PR? What about adding the invalid filling types?

IfcStore.get_element() might be what you're looking for.

**Comment by Gorgious56** [comment]
Yeah I should have pushed as a draft first, I wanted to know if you were ok with how I did it. I'll start working on the other tests then :)

**Comment by Gorgious56** [comment]
@Moult I've added most of the test cases I think.
I'm having trouble with a couple of lines which I added in https://github.com/IfcOpenShell/IfcOpenShell/blob/7ead2c2a0b2e6a0fded5fe6816e0c15d3c5011e9/src/blenderbim/blenderbim/bim/operator.py#L675-L676
The tests seem to hiccup and fail when I uncomment these lines and I don't understand why. They're used to remove an opening's fillings relationships when the user deletes the opening object using the delete operator.
So this test fails https://github.com/IfcOpenShell/IfcOpenShell/blob/7ead2c2a0b2e6a0fded5fe6816e0c15d3c5011e9/src/blenderbim/test/bim/module/void/test_operator.py#L343-L360

**Comment by Gorgious56** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/1711 for reference

**Comment by Moult** [comment]
Doing a James Bond

**Comment by Gorgious56** [comment]
Wut ?? ><

**Comment by Moult** [comment]
Commit first ask questions later :D

**Comment by Gorgious56** [comment]
Haha I like that !
Does https://github.com/IfcOpenShell/IfcOpenShell/commit/24eac8ccdd174d3f5ade62795b088709266d5fbc mean we can start refactoring the tests using this syntax ?

**Comment by Moult** [comment]
Should be fixed. And yes, feel free to start refactoring the tests. One thing however yet to decide is how to organise them. Right now I have a single `test_feature.py` which triggers all tests in the feature/ subdir. This is probably a bad idea, as we want two abilities:

 1. Run only a single scenario, or a subset of a few scenarios and exclude everything else, very handy for debugging
 2. Run only scenarios pertaining to a module.

Probably an easy solution, just a convention needs to be established of how to structure the test files. Happy for you to go ahead and go for it :)

**Comment by Moult** [comment]
So the reasons the tests hiccuped (I assume you mean crashed or segfaulted) is because indeed the tests are doing their job :)

In short, if you `delete_opening_element(element)` then you do `for rel in element.HasFillings`, the element is already deleted, so element is now an empty pointer which crashes both Blender and the tests.

Two solutions:

 1. Remove fillings first, then delete the opening element (which I did)
 2. Just delete the opening element anyway, which should purge fillings in the process.

Unfortunately I can't quite choose the more simple second solution just yet because right now we must call everything through operators and the operator expects both an opening and a thing it is voiding. In the future, as #1711 slowly trickles through the system, it will be much easier to make these types of changes. Also, complex scenarios like this in theory would be described much more elegantly using domain language (I assume when you wrote this code, you might've needed to read the logic in the operators quite a few times to get a feel for what was happening, which is not a very good experience).

**Comment by Moult** [comment]
The good news is we have increasingly more (albeit slow) high level tests :) Therefore in the future when we want to do some serious gut-ripping, clever parametric whizbang features, etc, we can do so without fear. By the way, you might want try writing tests first, then writing the code - it's a fun trick to learn, but super powerful when you get the hang of it!

**Pull request merged**
