### PR TITLE
#842 - IfcAlignment - Clothoid transition implementation

### PR DESCRIPTION
**Pull request by civilx64**
Initial implementation of alignment transition curves, per discussion on #842.
At this time, only the Clothoid has been confirmed to return the correct X & Y coordinates.

### CODE REVIEW

**Comment by aothms** [comment]
Awesome, thanks @civilx64! I'm just going to merge this as is, and then try to piece things together so that the ifcopenshell.geom.create_shape() function will direct either to this set of functions or to the C++ based conversion functions depending on content. What do you think @Moult is that a quick way to work towards support in BlenderBIM?

**Comment by Moult** [comment]
@aothms sure thing :) From your description, it sounds as though I need to make no changes and create_shape will "just work". Will the iterator also "just work"?

**Comment by civilx64** [comment]
@aothms @Moult one potential obstacle before it will "just work" is that an IfcAlignment is topologically just a series of edges between vertices joined into a wire. Looking at the BlenderBIM importer code it appears that Blender meshes are built from vertices and faces, but these entities would be vertices only. If in fact this is an issue then one solution might be to extrude a unit square maybe 10mm per side along the alignment to provide the faces for mesh creation in Blender. (Circular profile extrusion would work also but be much heavier in terms of face count.)

Also as you might have noticed the code is returning a list of gp_Pnts rather than a wire. Feel free to adjust as necessary. When testing it was easier for me to print and review x,y coordinates on the points rather than using something like Topo_Explorer to get a vertex list from the wire.

**Comment by Moult** [comment]
The code I think you're looking at is the default for 3d bodies, but there is code which handles 2d (or 3d minus faces). Should be solvable :) @aothms can you let me know what's required to test IFC 4.3 and up? Which express file should I get? I assume I can just so "load from express" prior to loading the file? @civilx64 have you got any test files I can try?

**Comment by aothms** [comment]
@Moult rc1 and rc2 are baked into the binaries. Only for rc3 and newer you need to supply and parse the exp schema file.

**Comment by aothms** [comment]
@Moult I dropped them an email to invite you to the test file repos. Also see #1480

**Comment by civilx64** [comment]
>  @civilx64 have you got any test files I can try?

I have two test files that I have been working with but they are 4.1 as I exported from commercial software.  I was thinking I would manually edit both to align with 4.3 rc3 and store both versions of both files in the [files repo](https://github.com/IfcOpenShell/files).

**Comment by aothms** [comment]
But also, all three of us have access to the IFCRail/IFC-Rail-Unit-Test repo. Isn't there something that we can use? RC3 is not final either. There is going to be an RC4. And who knows what comes after that.

**Comment by civilx64** [comment]
Yes, I had not been to the unit test repo in a while but after reviewing just now it should work nicely for verifying the IFCOS / BlenderBIM implementation.

**Pull request merged**
