### PR TITLE
IfcOpenShell WASM module

### PR DESCRIPTION
**Pull request by aothms**
In case you haven't seen, there is now a fully feature complete (but a bit on the heavy side) IfcOpenShell WASM module leveraging the awesome pyodide project (which is a fully compatible python interpreter in the browser using WASM).

This means you can access the extensive IfcOpenShell python API fully client-side and interact seamlessly with it through javascript.

https://github.com/IfcOpenShell/wasm-preview

These are the changes for the nix/build-all script to emit a WASM build.

The complete instructions are then for building the wasm wheel:

```sh
mkdir build && cd build
git clone https://github.com/IfcOpenShell/IfcOpenShell
git clone https://github.com/pyodide/pyodide

pyodide/run_docker
cd pyodide
cd emsdk/
make clean # in case the container was previously ran we need to reinstall emsdk
cd ..
make && pip install ./pyodide-build
cd ..
cp IfcOpenShell/pyodide/meta.yaml .
PYODIDE_ROOT=/src/pyodide \
PATH=/src/pyodide/emsdk/emsdk:/src/pyodide/emsdk/emsdk/node/14.18.2_64bit/bin:/src/pyodide/emsdk/emsdk/upstream/emscripten:$PATH \
python -m pyodide_build buildpkg --continue meta.yaml

# doesn't really work, but we can take it from here
cd build/ifcopenshell-0.7.0/package
cp ../../../IfcOpenShell/pyodide/setup.py .
python setup.py bdist_wheel
ls dist/IfcOpenShell-0.7.0-py3-none-any.whl
```

### CODE REVIEW

**Comment by tranhoangkhuongvn** [comment]
Hi @aothms I run into this error when assigning the path to PYODIDE_ROOT as below. Appreciate it if you can have a look on this. I am building this on Ubuntu 22.04.3 LTS 64 bit.

Thank you

`khuong@45f07b5c90fb:/src$ PYODIDE_ROOT=/src/pyodide PATH=/src/pyodide/emsdk/emsdk:/src/pyodide/emsdk/emsdk/node/16.20.0_64bit/bin:/src/pyodide/emsdk/emsdk/upstream/emscripten:$PATH python -m pyodide_build buildpkg --continue meta.yaml 
[2024-01-18 05:35:01] Building package ifcopenshell...                                                                                                         
[2024-01-18 05:35:01] Failed building package ifcopenshell in 0.0 seconds.                                                                                     
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/src/.docker_home/.local/lib/python3.11/site-packages/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/src/.docker_home/.local/lib/python3.11/site-packages/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/.docker_home/.local/lib/python3.11/site-packages/pyodide_build/buildpkg.py", line 959, in main
    build_package(args.package[0], build_args, args.force_rebuild, args.continue_)
  File "/src/.docker_home/.local/lib/python3.11/site-packages/pyodide_build/buildpkg.py", line 855, in build_package
    _build_package_inner(
  File "/src/.docker_home/.local/lib/python3.11/site-packages/pyodide_build/buildpkg.py", line 695, in _build_package_inner
    raise OSError(
OSError: Cannot find source for rebuild. Expected to find the source directory at the path /src/build/ifcopenshell-0.7.0, but that path does not exist.
`

**Comment by aothms** [comment]
> Expected to find the source directory at the path /src/build/ifcopenshell-0.7.0, but that path does not exist. 

@tranhoangkhuongvn sorry it's been a while since I looked into this. First thing to try, can you try without `--continue` maybe that doesn't work for a first build.

**Comment by tranhoangkhuongvn** [comment]
Thanks very much @aothms , that does help a bit, it was able to run the build but later stuck at this error:

`Building IfcOpenShell:
Configuring python 3.11.3 wrapper...
Building: cgal libxml2 json python freetype boost occ IfcParse IfcGeom IfcOpenShell-Python
----------------------------------------------------------------------
configure: cmake /src/build/ifcopenshell-0.7.0/cmake -DUSE_MMAP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBOOST_ROOT=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/boost-1.80.0 -DGLTF_SUPPORT=ON -DJSON_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/json -DBoost_NO_BOOST_CMAKE=On -DADD_COMMIT_SHA=Off -DWASM_BUILD=On -DCGAL_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/cgal-5.3/include -DGMP_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/include -DGMP_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/lib -DMPFR_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/include -DMPFR_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/lib -DOCC_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/include/opencascade -DOCC_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/lib -DCOLLADA_SUPPORT=Off -DLIBXML2_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/include/libxml2 -DLIBXML2_LIBRARIES=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/lib/libxml2.a -DHDF5_SUPPORT=Off -DPYTHON_LIBRARY=/src/pyodide/cpython/installs/python-3.11.3/lib/libpython3.11.a -DPYTHON_MODULE_INSTALL_DIR=/src/build/ifcopenshell-0.7.0/package -DPYTHON_INCLUDE_DIR=/src/pyodide/cpython/installs/python-3.11.3/include/python3.11 -DCMAKE_INSTALL_PREFIX=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/ifcopenshell/tmp -DUSERSPACE_PYTHON_PREFIX=Off -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CROSSCOMPILING_EMULATOR=/src/pyodide/emsdk/emsdk/node/16.20.0_64bit/bin/node
CMake Deprecation Warning at CMakeLists.txt:28 (cmake_policy):
  The OLD behavior for policy CMP0078 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


**CMake Error at CMakeLists.txt:1057 (add_subdirectory):
  The source directory

    /src/build/ifcopenshell-0.7.0/src/svgfill

  does not contain a CMakeLists.txt file.**


emcmake: error: 'cmake /src/build/ifcopenshell-0.7.0/cmake -DUSE_MMAP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBOOST_ROOT=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/boost-1.80.0 -DGLTF_SUPPORT=ON -DJSON_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/json -DBoost_NO_BOOST_CMAKE=On -DADD_COMMIT_SHA=Off -DWASM_BUILD=On -DCGAL_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/cgal-5.3/include -DGMP_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/include -DGMP_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/lib -DMPFR_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/include -DMPFR_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/lib -DOCC_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/include/opencascade -DOCC_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/lib -DCOLLADA_SUPPORT=Off -DLIBXML2_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/include/libxml2 -DLIBXML2_LIBRARIES=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/lib/libxml2.a -DHDF5_SUPPORT=Off -DPYTHON_LIBRARY=/src/pyodide/cpython/installs/python-3.11.3/lib/libpython3.11.a -DPYTHON_MODULE_INSTALL_DIR=/src/build/ifcopenshell-0.7.0/package -DPYTHON_INCLUDE_DIR=/src/pyodide/cpython/installs/python-3.11.3/include/python3.11 -DCMAKE_INSTALL_PREFIX=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/ifcopenshell/tmp -DUSERSPACE_PYTHON_PREFIX=Off -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CROSSCOMPILING_EMULATOR=/src/pyodide/emsdk/emsdk/node/16.20.0_64bit/bin/node' failed (returned 1)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/src/build/ifcopenshell-0.7.0/nix/build-all.py", line 902, in <module>
    compile_python_wrapper(
  File "/src/build/ifcopenshell-0.7.0/nix/build-all.py", line 874, in compile_python_wrapper
    run_cmake("",
  File "/src/build/ifcopenshell-0.7.0/nix/build-all.py", line 322, in run_cmake
    run([*wasm, "cmake", P, *cmake_args, f"-DCMAKE_BUILD_TYPE={BUILD_CFG}"], cwd=cwd)
  File "/src/build/ifcopenshell-0.7.0/nix/build-all.py", line 278, in run
    raise RuntimeError(f"Command `{' '.join(cmds)}` returned exit code {proc.returncode}")
RuntimeError: Command `emcmake cmake /src/build/ifcopenshell-0.7.0/cmake -DUSE_MMAP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBOOST_ROOT=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/boost-1.80.0 -DGLTF_SUPPORT=ON -DJSON_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/json -DBoost_NO_BOOST_CMAKE=On -DADD_COMMIT_SHA=Off -DWASM_BUILD=On -DCGAL_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/cgal-5.3/include -DGMP_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/include -DGMP_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/gmp-6.2.1/lib -DMPFR_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/include -DMPFR_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/mpfr-3.1.6/lib -DOCC_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/include/opencascade -DOCC_LIBRARY_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/occt-7.5.3/lib -DCOLLADA_SUPPORT=Off -DLIBXML2_INCLUDE_DIR=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/include/libxml2 -DLIBXML2_LIBRARIES=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/libxml2-2.9.11/lib/libxml2.a -DHDF5_SUPPORT=Off -DPYTHON_LIBRARY=/src/pyodide/cpython/installs/python-3.11.3/lib/libpython3.11.a -DPYTHON_MODULE_INSTALL_DIR=/src/build/ifcopenshell-0.7.0/package -DPYTHON_INCLUDE_DIR=/src/pyodide/cpython/installs/python-3.11.3/include/python3.11 -DCMAKE_INSTALL_PREFIX=/src/build/ifcopenshell-0.7.0/build/Linux/wasm/install/ifcopenshell/tmp -DUSERSPACE_PYTHON_PREFIX=Off -DCMAKE_BUILD_TYPE=RelWithDebInfo` returned exit code 1
ERROR: build script failed                                                                                         
    python nix/build-all.py --without-hdf5 --without-opencollada --without-swig --without-pcre -v --wasm --py310   
IfcOpenShell-Python                                                                                                
    cp pyodide/setup.py .   `

**Comment by aothms** [comment]
There's an easy answer to that.

    git submodule update --init --recursive

**Comment by tranhoangkhuongvn** [comment]
thanks for your prompt response @aothms  but where should I run that command?

**Pull request merged**
