### PR TITLE
Ensure polygons are always coplanar

### PR DESCRIPTION
**Pull request by s-leger**
fix issue #1481
May adopt a bmesh approach instead ?

### CODE REVIEW

**Comment by s-leger** [comment]
Bmesh approach is way faster (and cleaner) than modifier based one.

**Comment by Moult** [comment]
Fantastic approach! Great solution.

**Comment by aothms** [comment]
while I like the approach and I'm sure it will work in a lot of cases. The tolerance in IFC is linear, not angular. So for large faces it may still pose problems.

Is there anyway you can make the `triangulate()` op work only on a subset of faces? For every polygon you can loop over the vertices and take the dot product with the polygon normal. Take min and max of those dot product values. If the difference between min and max is greater than the model tolerance, the face needs to be triangulated.

**Comment by s-leger** [comment]
Make sense, triangulate() takes faces as input, so we may filter those faces. 
Agree that we must stronger approach to handle all cases given the fact that we are working in single precision.
Probably a any([abs(dot) > tol]) will do the trick. 
Looking for anybody able to implement this, my attempt to do such test rely on matrix multiplication (matrix located at first vertex with normal as z axis) @ vertex.coordinate absolute z distance, but maybe dot method will be faster - wich is a hard requirement as every single polybon must be checked.

**Pull request merged**
