### PR TITLE
Fix normal duplication of linked aggregate

### LINKED ISSUE #4430: `Cntl+D` created a 'Linked Aggregate'
I duplicated `Cntl+D` (not a `Shift+Ctrl+D`) the aggregate in the following video. As you can see it says it's a 'Linked Aggregate'.  I would assume it would not be. 

file: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/97c36c51f17ff06a7e5e06390e11743bbb949016/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9add4b19-6056-4dc7-b894-a285cccde698

ping @brunoperdigao

### PR DESCRIPTION
**Pull request by brunoperdigao**
This PR aims to fix #4430 and #4435

### CODE REVIEW

**Comment by brunoperdigao** [comment]
Hi, @theoryshaw Did you get the chance to test this? Let me know if I can merge it.

**Comment by theoryshaw** [comment]
I did not get a chance yet.  I can later this week-will be 'back in the office'. :)

**Comment by brunoperdigao** [comment]
@brunoperdigao Do you think I can merge this PR? I'd like to get this done before working on [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/4b56b341243d6b0eed82e8533848b124e82e1344#commitcomment-141478958)

**Comment by theoryshaw** [comment]
Apologies!, this one slipped through.  Yes, this works great!  Just tested.

**Pull request merged**
