### PR TITLE
Windows batch script enhancements

### PR DESCRIPTION
**Pull request by Stinkfist0**
Make possible to invoke run-cmake.bat, build-ifcopenshell.bat, and install-ifcopenshell.cmd directly from File Explorer or command prompt without VS env vars set, if BuildDepsCache file exists, by utilizing CMake's --build functionality.

### CODE REVIEW

**Comment by Stinkfist0** [comment]
Oops, accidentally deleted this branch.

**Comment by aothms** [comment]
I like these changes, this will simplify things quite a bit. Thanks!

1) I would recommend not to read cached variables from both files, as I am bit worried that variables would be mixed between the two architectures if they are absent in `x64`, how about using a loop sorted on atime/mtime, e.g:

~~~
@echo off

for /f "tokens=*" %%f in ('dir BuildDepsCache-*.txt /o:-n /t:a /b') do (
    echo %%f
    goto :break_loop
)

:break_loop
~~~

2) Just out of curiosity, is this a typo or does this trailing dot have some significance: `if exist BuildDepsCache-x64.txt.`

3) Maybe it is an idea to show an error message if `%GEN_SHORTHAND%` is not defined. This is what would happen when a user runs the script by clicking in their explorer without invoking it from the cli first, am I right?

**Comment by Stinkfist0** [comment]
Yeah, I'll do these enhancements. Regarding the trailing dot, it is intentional (it is "best practice" of some sort, even `if /?` uses it in the example, can't recall the actual reason though...) and actually the line that misses it has a typo.

**Comment by Stinkfist0** [comment]
The fixes/enhancements are in.

**Comment by aothms** [comment]
Great, thanks again Ali!

**Pull request merged**
