### PR TITLE
Relocate the bim pt object material panel in the material context

### PR DESCRIPTION
**Pull request by theoryshaw**
relative to the following idea...

"can we move the object material panel to the Material's tab rather than the Object Properties? It makes a bit more sense that bit of info in the same area."

https://github.com/IfcOpenShell/IfcOpenShell/issues/2418#issuecomment-1268380605

### CODE REVIEW

**Comment by Moult** [comment]
I've been avoiding this since the Blender materials panel actually doesn't correlate very well to the concept of an IFC material. It only represents a single material, style, or material with style attached. I can't think of a UX to make it represent material sets, profiles, constituent settings, and layers. E.g. what happens if you remove the active material from the object? The material should exist, so is the Object Material panel independent of the rest of the data in the materials tab? Also, there's a lot of Blender boilerplate with shaders that pushes our IFC panels to the bottom which isn't very nice either.

The ideal scenario is to invent our own IFC Materials tab, but I don't think that's currently possible in Blender.

**Comment by Moult** [comment]
What if, what if... what if we used the Texture Tab instead? Would that be a crazy idea?

**Comment by Gorgious56** [comment]
FWIW I _think_ the panel may be displayed in both contexts with `bl_options = {"INSTANCED"}`

https://docs.blender.org/api/current/bpy.types.Panel.html#bpy.types.Panel.bl_options

**Comment by Moult** [comment]
I caved and switched it, and at least it seems to appear at the top of the screen for me.

**Pull request closed without merging**
