### PR TITLE
Command Line Interface and MS Project Resource Parsing

### PR DESCRIPTION
**Pull request by HassanEmam**
Hello,

I have implemented the CLI as discussed in the previous PR discussion
The MS Project resource parsing is also included in this amendments.

### CODE REVIEW

**Comment by HassanEmam** [comment]
This is how the CLI works

image

**Comment by HassanEmam** [comment]
image

**Comment by Moult** [comment]
Awesome! BTW is this test code? https://github.com/IfcOpenShell/IfcOpenShell/pull/1845/files#diff-c26c3a2b425fe29242637442d33c84b40e299d8618f2812c29c5257338b3e3fdR168-R173

**Comment by HassanEmam** [comment]
Yes it is I will remove it; I always forget to remove my final tests

**Comment by Moult** [comment]
Cool - happy to merge after removal :D

**Comment by HassanEmam** [comment]
cheers, I have removed the test code and added an additional check on output file value before writing to avoid failures

**Pull request merged**
