### PR TITLE
Section cutaway plane cut line decoration

### PR DESCRIPTION
**Pull request by Gorgious56**
Re the discussion on #2547

This is a proposal to display a thick black line at the section limit on the mesh, when using the temporary section cutaway tool.

Here it is in action

Animation3

The PR adds a new parameter to tweak the line width in the output properties. It can be set to 0 to display like it was before. The value is in Blender units, but due to how it's setup I think it generates a line double the width of what is set in the field. (absolute on signed distance)

image

Pros : Realtime, does not create any new geometry

Cons : 

Doesn't work when viewing the section orthogonally, 

image

Doesn't work well for faces parallel or next to parallel to the section plane (it creates black surfaces instead of a thick line since the effect is distance base)

image

Edit : Also it doesn't work with more than one section object. I think I have a solution if it's really a problem but it requires a bit more tinkering with the node group.

### CODE REVIEW

**Comment by Moult** [comment]
This is AWESOME! I have been looking for functionality like this in Blender for a very, very long time! I'll need to investigate the incantation you used to make it happen :)

**Comment by Gorgious56** [comment]
@Moult hehe I only added a couple of nodes actually :)

A compare math node to get the distance to the section plane

image

And a mix shader to display the black line when the distance threshold is met

image

**Comment by schroef** [comment]
I see this implementation has issue when multiple section cuts are in the scene. The section cuts have loop from on to the other. But the line decoration is only added later and thus looks weird

issue line decorator-multiple section cuts pn

**Comment by Gorgious56** [comment]
Yes the black lines features only supports one section cut as far as I remember. Theoretically I think it could be extended to support multiple cuts. In the meantime you can disable it by setting the line width to 0

**Comment by schroef** [comment]
Yeah, I got it sort of working. But the issue is that I need to add many extra nodes to get all the cuts also working on all the line decorations. If I use a compare node and then use the section compare the t works. But the issue afterwards is when I try to clean all sections or remove a single section.
Getting the corrects nodes and removing it and the reconnecting all the proper nodes to each other again is a pain. Currently ingave a setup where the line decorator is added after the section compare. The line don't follow the shape properly.

I'm going to test what happens if I add the line to the material inside the section compare group. I think this makes cleaning and removing each section easier. My current setup uses a lot of extra code just for line decoratie. It's a mess.

I've also got the section shader working on collections which actually have a material. The current version doesn't do that. It only works on objects without a material.

**Comment by schroef** [comment]
Okay did a test today again and i got it to work. Though i made the setup manually. I think this can be done using code as well. Atleast in theorie. It also looks cleaner than my first try and is easier to clean afterwards. Where this new approach only needs to remove the compare node and text coor node. But the other would have cycle over many more nodes.

This was my first try. Lines get cut properly per section. But making this work by code is a nightmare!
fix for crossing lines

This is my second approach. the line decorator is moved inside the compare node. There it is mixed the the material and transparent node. Then because i simply add the sections one after the other. The line decorator still work nicely. Plus cleaning each section is easy. Its the same as the original, where the tex coord and compare node are removed.

Example with 3 sections. Each section is placed after the other and connects in tandem
line-decorator-inside-section-compare-1

This is how i setup the compare node inside
line-decorator-inside-section-compare-0

Now need to find the proper method of laying out the nodes. So it looks organized. Issue is the spaghetti going all over the place

**Comment by Gorgious56** [comment]
Ooh this looks nice ! IMO node spaghetti is not a big deal. In the first
iteration of the section tool all nodes were placed at 0,0,0. Most users
won't dig into the node tree and those that will should know how to
navigate around a messy node tree. Where we don't want spaghetti is in the
code though ^^

**Comment by schroef** [comment]
Well a bit of tidying up and it looks clean now. Also got the deletion work now of single sections and reconnecting everything. Was a bit of a hustle since the last and the first in the section compare line are connected to different nodes. But with some if elif and else options, i got that sorted out now.

**Pull request merged**
