### PR TITLE
Converting quantities to project units to fix #3025

### LINKED ISSUE #3025: If an imperial file, have .bim.calculate_all_quantities() calculate imperial values
If an imperial file, have `bim.calculate_all_quantities()` calculate imperial values

Currently if calculates metric values.

### PR DESCRIPTION
**Pull request by Andrej730**
Added conversion to project units at the end of calculations - currently all the length/area/volume units are calculated in meters and they need to be converted if the project is using some other unit or prefix.

Please take a look - I haven't worked on this part of code before.

### CODE REVIEW

**Comment by Moult** [comment]
At a glance you're using the right functions. Have you tested it? If so, feel free to merge. Would be nice to write one or two tests for this.

**Comment by theoryshaw** [comment]
seems to work on my side!

image

**Comment by maxfb87** [comment]
@Andrej730 ok, i think it is ok!
Maybe it is also useful to compare it with  the solution already available in /blenderbim/bim/module/pset/operator.py
in lines 374-408 but maybe this is better because it reads directly from the ifc file...

Also, maybe, for doing better tests, the function "convert_to_project_units" should be a tool function?

Just thinking loud btw, for me it can be merged :-)

**Review by maxfb87 — APPROVED** [review]

**Comment by Andrej730** [comment]
> Maybe it is also useful to compare it with the solution already available in /blenderbim/bim/module/pset/operator.py
Missed that one! I'll connect them all to the same tool method.

**Review by maxfb87 — APPROVED** [review]

**Review by maxfb87 — APPROVED** [review]

**Pull request merged**
