### PR TITLE
Edit profile based representations with TAB

### PR DESCRIPTION
**Pull request by Gorgious56**
Following #2983

This allows users to TAB into edit mode when one profiled-based (SweptSolid) representation is selected.
I didn't know how to check if the profile editor was active so I added a little helper in blenderbim.tool.Profile to check if the ProfileDecorator is installed. I guess it's a weak way to check if edition is going on but it seems reliable enough.

### CODE REVIEW

**Comment by Gorgious56** [comment]
I guess next step is to remove the SHIFT + E shortcut which is now superfluous ? 

I would keep this one though, since it lets user go into local front mode and quit edition without saving the changes.
image

**Comment by Gorgious56** [comment]
This fails for railing objects. How can I easily know if the active object is a railing object ? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/workspace.py#L209-L211 seems a bit overkill

**Comment by Moult** [comment]
Sorry I'm late catching up on these PRs.

All profile meshes (or other magic meshes) have their mesh type set e.g. `mesh.BIMMeshProperties.subshape_type = "PROFILE"` - this _should_ correlate with a corresponding decorator. Does that help?

Agreed that Shift-E should be removed once Tab is implemented. Go ahead and merge when you think it's ready :)

**Comment by theoryshaw** [comment]
@Gorgious56 This is great, of course. 
It doesn't seem to work on ifcslab instances, however.  I might be missing something.

**Comment by Gorgious56** [comment]
I had a problem with slab not regenarating but I think I fixed it in a recent commit. Are you using the latest version ? Can you share a stripped down ifc file with the problematic slab ?

**Comment by theoryshaw** [comment]
It works with just starting a new demo file, and adding a slab instance...
[untitled.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11713122/untitled.ifc.txt)

**Comment by Gorgious56** [comment]
I think I found the problem but I hope there will be no unintended consequences.

**Comment by Plae-Blue-Dot** [comment]
Just tried the new update tab on horizontal elements, it's amazing thankyou @Gorgious56

**Comment by Plae-Blue-Dot** [comment]
Is it possible to extend this functionality to edit wall axis aswell?

normal wall:
image

Curve 2d / axis representation:
image

**Comment by Gorgious56** [comment]
I don't know about allowing to edit wall axis with TAB because there is a dedicated editing workflow specifically for walls with the Extend / Butt / Merge / etc. shortcuts. I don't know if editing the wall axis can be integrated well with these features. Especially because as per the schema I think the wall axis must stay along the local X axis which is hard to enforce if we let users mess with the vertices. @Moult what do you think ?

**Comment by Moult** [comment]
Agreed. It will take a bit more implementation to do properly. @Plae-Blue-Dot if you think its worth it feel free to create a bug to track it.

**Comment by Plae-Blue-Dot** [comment]
I think it is a nice to have, even if it is restrained in the x direction, absolutely not essential as we do have a workflow around walls
I made a issue here:

https://github.com/IfcOpenShell/IfcOpenShell/issues/3297

I think there is something natural about pressing tab and being able to edit if it all follows the same language, people are going to press tab to see what can be edited that way, but absolutely not important right now.

**Pull request merged**
