### PR TITLE
Use model-offset in IfcGeom::Kernel and add model-rotation

### PR DESCRIPTION
**Pull request by Blocovin**
I merge the pull request #672 into v0.6.0

And fix --center-model to makes it work independently of the serializer.

### CODE REVIEW

**Comment by Stinkfist0** [comment]
Minor note: this make the option/setting a geometry setting now instead of serializer option so the code and documentation would be good to be adjusted accordingly.

**Comment by Blocovin** [comment]
> Minor note: this make the option/setting a geometry setting now instead of serializer option so the code and documentation would be good to be adjusted accordingly.

I've updated the documentation

**Comment by Stinkfist0** [comment]
Great, also note that it's good to move this under `geom_options` instead of `serializer_options` in the code.

**Comment by Blocovin** [comment]
> Great, also note that it's good to move this under `geom_options` instead of `serializer_options` in the code so that they appear under the right section when `--help` is used.

Oh, sorry ! I didn't realize there were two sections. So I moved this under `geom_options`.

**Comment by Blocovin** [comment]
@aothms Is there a problem for accepting the merge request ?

**Comment by aothms** [comment]
@Blocovin sorry for the delay. This is definitely a wonderful PR, adding functionality and cleaning up existing (std::array usage, conversion to gp_Trsf in kernel for more general usage). It's just that it took me some time to review as I have the bad habbit of going through the PRs top to bottom in github (so in reverse order) and I have been too busy.

The only issue I can think of is that it doesn't somehow fail on 0;0;0;0. I'd expected OCCT to throw a ConstructionError but it actually happily creates a gp_Mat with NaNs ending up all the way in the serialized output of the matrices. Perhaps that should be fixed upstream in OCCT. I don't think it's a blocker for this PR.

Wonderful work. Hope to welcome your contributions more.

**Pull request merged**
