### PR TITLE
Blender ifc 2.80rc1 collections enhancement

### PR DESCRIPTION
**Pull request by elmopl**
This fix helps with importing by creation nested collections according to layers that can be retrieved from IFC file.

image

### CODE REVIEW

**Comment by aothms** [comment]
Many thanks for this! Sorry for the delay. I hope to be able to have a look in the coming week.

**Comment by Moult** [comment]
I have tested a quick import and it seems to work great! See attached import.

2019-09-03-213145_1214x1048_scrot

It also seems as though we have both figured that Blender's collections feature does a great job of spatial decomposition! See: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcblenderexport

If @aothms is OK with merging this, I'd be happy to do so, along with test it on a real project that we're doing in Blender right now :) And perhaps implement more tricks such as reusing mesh instances, and an option for putting the IFC class in the name as well as a custom property (it isn't necessary, but we found when it helps modelers stay organised and navigate the outliner)

**Comment by aothms** [comment]
> If @aothms is OK with merging this

Yes, yes, yes.

> And perhaps implement more tricks such as reusing mesh instances

There is a bug related to that. #661 https://sourceforge.net/p/ifcopenshell/discussion/1782718/

**Comment by elmopl** [comment]
> And perhaps implement more tricks such as reusing mesh instances

Looking at code it seems like it does that when loading (or am I missing something?)

        # MESH CREATION
        # Depending on version, geometry.id will be either int or str
        mesh_name = 'mesh-%r' % ob.geometry.id
        if mesh_name in bpy.data.meshes:
            me = bpy.data.meshes[mesh_name]
        else:

> IFC class in the name as well as a custom property

I was wondering if that would be helpful. This is the first time I am exposed to IFC files at all, so I don't really know all the quirks and relations you can store in that file.
I was wondering how much information is lost and whether it would be possible to pull out all data that IFC file contains so that you could re-save it without losing any data (or ideally without changing internal structure at all).

From other things I was also thinking about adding extra level  collection `geometry`.
Currently I found it really annoying when I loaded a model of house that IIRC I couldn't easily hide ceiling bits as they were in structure above collection with walls.
I could make that change before this gets merged (or after, don't really mind).

**Comment by Moult** [comment]
Also cherry picked the commits into v0.6.0 branch.

**Pull request merged**
