### PR TITLE
separated nested argument lists to avoid an error when compiling with…

### PR DESCRIPTION
**Pull request by iras**
… gcc.

### CODE REVIEW

**Comment by aothms** [comment]
Thanks, yeah, it's unfortunate that this doesn't result in an error in MS Visual Studio. Automated builds will help spot these issues in the future.

**Comment by Stinkfist0** [comment]
This should be valid C++11 syntax. Newer GCC should compile this AFAIK.

**Comment by aothms** [comment]
But then you would need to compile with `-std=c++11` which we do not do (thusfar).

**Comment by Stinkfist0** [comment]
Yup, just an observation.

**Pull request merged**
