### PR TITLE
Add instructions for install via conda.

### PR DESCRIPTION
**Pull request by civilx64**
Per #318.

### CODE REVIEW

**Comment by civilx64** [comment]
Oops, this doesn't include pythonocc, so the viewer does not work.  I will do some additional testing and update the README accordingly.

**Comment by aothms** [comment]
> Oops, this doesn't include pythonocc, so the viewer does not work. I will do some additional testing and update the README accordingly.

Great, thanks. I went ahead and merged this because your qt5 changes were based on top of this.

Unfortunately at the moment the conda ifcopenshell package links to an old version of occ, so you have to get a pretty old pythonocc as well in order to avoid conflicts.

**Comment by johannesmichael** [comment]
> Unfortunately at the moment the conda ifcopenshell package links to an old version of occ, so you have to get a pretty old pythonocc as well in order to avoid conflicts

Any plans on updating this? Because I really have trouble to get the jupyter renderer to work together with ifcopenshell.

Johannes

**Comment by aothms** [comment]
> Any plans on updating this?

It has been updated [1]. We now link to OCE 0.18.3 which is the latest OCE release. @johannesmichael  what's the issue you're experiencing?

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/conda/meta.yaml#L30

**Comment by johannesmichael** [comment]
Thanks, Thomas

I had several problems, I was thinking, they coul be related to that question here.
Two things:

1. If I have pythonocc-core 0.17.3 installed, I cannot upgrade ifcopenshell.
After creating a new env and installing ifcopenshell I try to:

conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1
Solving environment: done

Package Plan

  environment location: \Anaconda3\envs\ifc

  added / updated specs:
    - pythonocc-core==0.18.1


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge
    jpeg:            9b-vc14_2             conda-forge  [vc14]
    openssl:         1.0.2o-vc14_0         conda-forge  [vc14]
    pyqt:            5.6.0-py36h764d66f_7  conda-forge
    pythonocc-core:  0.18.1-py36_vc14_110  pythonocc    [vc14]
    qt:              5.6.2-vc14_1          conda-forge  [vc14]
    sip:             4.18.1-py36h6538335_0 conda-forge
    smesh:           6.7.5-vc14hfb33b19_0  pythonocc    [vc14]

The following packages will be REMOVED:

    ifcopenshell:    0.6.0a1-py36_vc14_0   ifcopenshell [vc14]

The following packages will be DOWNGRADED:

    freetype:        2.8.1-vc14_0          conda-forge  [vc14] --> 2.7-vc14_1            conda-forge [vc14]
    oce:             0.18.3-vc14_3         oce          [vc14] --> 0.18.2-vc14h5f3c129_1 oce         [vc14]
    tbb:             2018_20171205-vc14_0  conda-forge  [vc14] --> 2017_20170226-vc14_0  conda-forge [vc14]

it would remove ifcopenshell. 
ALso I had this problem on pythonocc side: [https://github.com/tpaviot/pythonocc-core/issues/559](url)


The other issue is, that I get on the Jupyter Notebook Viewer a Tesselator Error on number of arguments. But I thought, it could be related to the version issue.

Thanks for helping
Johannes


# Name             Version                   Build  Channel
certifi            2018.10.15            py36_1000    conda-forge
freeimageplus      3.17.0                   vc14_0  [vc14]  dlr-sc
freetype           2.8.1                    vc14_0  [vc14]  conda-forge
gl2ps              1.3.8                    vc14_3  [vc14]  dlr-sc
icu                58.2                     vc14_0  [vc14]  conda-forge
ifcopenshell       0.6.0a1             py36_vc14_0  [vc14]  ifcopenshell
libboost           1.67.0               hd9e427e_4
libpng             1.6.34                   vc14_0  [vc14]  conda-forge
oce                0.18.3                   vc14_3  [vc14]  oce
pip                18.1                  py36_1000    conda-forge
python             3.6.6                he025d50_0    conda-forge
setuptools         40.6.2                   py36_0    conda-forge
tbb                2018_20171205            vc14_0  [vc14]  conda-forge
vc                 14                            0    conda-forge
vs2015_runtime     14.0.25420                    0    conda-forge
wheel              0.32.3                   py36_0    conda-forge
wincertstore       0.2                   py36_1002    conda-forge
xz                 5.2.4             h2fa13f4_1001    conda-forge
zlib               1.2.11                   vc14_0  [vc14]  conda-forge

**Comment by aothms** [comment]
It seems pythonocc hasn't been updated for a while and needs a slightly older version of OCE. I mean, you do not need to use conda, you can just get the pythonocc from conda and get the ifcopenshell binaries from here [1] and put it in the site packages dir manually. The good thing is that IfcOpenShell communicates with pythonOCC using string-serialized shapes, so binary compatibility is not an issue there.

Or, you can probably instruct conda not to do dependency resolution and just drop the ifcopenshell package in there. The pythonOCC and ifcopenshell conda packages both depend on oce 0.18.x so they should be binary compatible. But not sure at all whether this approach is going to work.

[1] https://github.com/IfcOpenBot/IfcOpenShell/commit/ba274bb1642d7be236199dbfa5031746aee10b3d#commitcomment-31291366

**Comment by johannesmichael** [comment]
Thanks, didn't know the download option. Took it from there. Everything looks fine, but I have problems with the jupyter(hub) notebook usage. But I will place my question  there at ifcopenshell-jupyterhub.

**Pull request merged**
