### PR TITLE
Add IFC4 support for functions of get_connected_to and get_connected_from in util.system

### PR DESCRIPTION
**Pull request by chunchk**
Due to the limitations of the original code base, support for IFC4 versions had been lacking. To address this, we have updated the relevant functions to better align with modern requirements. This new commit incorporates changes that represent a different approach to the problem.

### CODE REVIEW

**Comment by Moult** [comment]
If I'm reading this right, doesn't that mean that it'll now break for IFC2X3?

**Comment by chunchk** [comment]
I thought you want it to be IFC4 version only
but I think I can make it compatible with IFC2X3 as well

**Comment by chunchk** [comment]
@Moult 
Will adding a condition be better? or is there any other way to get the IFC schema?

**Comment by Moult** [comment]
I guess you can check the schema using `element.wrapped_data.file.schema`, then indeed use an if statement.

**Comment by chunchk** [comment]
> 

Got it~
And I found something interesting, maybe I can further optimise it

**Comment by aothms** [comment]
There's also this ugly approach to get schema name from instance (which doesn't depend on file), we should really streamline this. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L143

**Pull request merged**
