### PR TITLE
Ifc Systems Navigator (WIP)

### PR DESCRIPTION
**Pull request by chuncahk**
It is still in WIP. **Please do not merge until it is ready**.

I am facing some problems I don't know how to solve, it would be very appreciated if there is a helping hand.
1. I don't know how to integrate the sorting function correctly.
2. Is there any method to register multiple sub-panels?

### CODE REVIEW

**Comment by Andrej730** [comment]
I don't think creating panels dynamically is a good approach here, I think all panels should be registered when you start the addon and then update their UI as IFC data changes.

1) Sorting panels or ...?
2) register_class?

**Comment by chuncahk** [comment]
The main panel is registered when the addon starts.....but all the subpanels are registered as per the number of IfcSystem in the file. 
The script was running fine when I test it in Blender, but I don't know how to implement merge this into the main branch....
1. What the script doing is extracting all the name of IfcSystems in the file and sort them using def get_ifc_systems_in_current_file()...but I am not sure where should I place it
2. I am not sure how should I register all the sub panels....

**Comment by Gorgious56** [comment]
Maybe sub-panels is not the right approach here, you could study how dynamic collections are done in the addon, for example the pset elements. 

image

rows are added dynamically to the main panel layout and then you can click on the pen icon to enable edition. 
You can also use UIList for 1d or tree-like structure

image

**Comment by chuncahk** [comment]
> 

Thanks for the insight, I agree that the current approach may not be the best.
Dynamic collections seems possible, but I want all the system types can be collapsed so it won't be too long in the UI.

**Comment by Moult** [comment]
The UI Lists can handle tree structures. It's implemented in quite a few spots - like in schedules, or the spatial manager.

**Comment by chuncahk** [comment]
> 

Then using UIList sounds more promising
Is it possible to add buttons inside the UIList?

**Comment by Andrej730** [comment]
@chuncahk sure

image

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/profile/ui.py#L115-L123

**Comment by chuncahk** [comment]
> @chuncahk sure
> 
> image
> 
> https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/profile/ui.py#L115-L123

Thank you. I'll see what I can do

**Comment by chuncahk** [comment]
Hi guys, I need a little more help please.
I am taking spatial manager as reference to build a tree structures UIList.
but the list goes like this....did I do something wrong...? Is there a simpler example for tree structure UIList?
Thanks

image

**Comment by Andrej730** [comment]
> it is basically faking indent instead of a real tree structure uilist

@chuncahk yes, it's just adding indent using "BLANK" icons depending on hierarchy level.

image

**Comment by chuncahk** [comment]
I need a second thought about the approach base on the new version of Bonsai

**Pull request closed without merging**
