### PR TITLE
ifccsv - support importing enum properties #4608

### PR DESCRIPTION
**Pull request by Andrej730**

### CODE REVIEW

**Comment by ppaawweeuu** [comment]
Works fine, Can we merge it, pls :)

**Comment by Moult** [comment]
I just took a look at this, is there a reason this isn't implemented in ifcopenshell.util.selector.set_element_value and uses this hack instead?

**Comment by Andrej730** [comment]
> I just took a look at this, is there a reason this isn't implemented in ifcopenshell.util.selector.set_element_value and uses this hack instead?

to use the same concatentation string that was used to serialize the list for enum property

**Comment by Andrej730** [comment]
Superseded by c9847ca

**Pull request closed without merging**
