### PR TITLE
fix: add conditional #include <windows.h> for certain files breaking …

### PR DESCRIPTION
**Pull request by Krande**
…with boost v1.78+ based on discussion in https://github.com/IfcOpenShell/IfcOpenShell/issues/2361

### CODE REVIEW

**Comment by aothms** [comment]
Thanks :)

I think the only include of boost/regex is here 

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IfcGeomFilter.h#L31

Did you also try sliding it in right before that in that header file?

**Comment by Krande** [comment]
I think I tried that first. Although I did try a lot of different things at first when I was experimenting. So I can make another check just to be sure. It would be nice to isolate the hack to a single location :)

**Comment by Krande** [comment]
Oh, I probably did not try the `BOOST_REGEX_NO_W32`. It seems adding only that to the line before including regex solves everything :) 

I'll let the local test finish before updating my PR

**Comment by Krande** [comment]
@aothms I've made modifications now so that the only change is adding `BOOST_REGEX_NO_W32`. It worked on my local test, but I haven't tested it on a github actions workflow, yet, so we'll have to see how it performs after merge. But if you're happy, then I can do a "squash and merge" :)

**Comment by aothms** [comment]
Thanks a lot @Krande

**Pull request merged**
