### PR TITLE
docs: update Doxyfile, remove duplicate docs

### PR DESCRIPTION
**Pull request by dirkolbrich**
- specify ./output/doxygen as main path for output
- use relative paths for subfolder output

This allows to build the docs as local html output with minor adjustments to the Doxyfile.

### CODE REVIEW

**Comment by dirkolbrich** [comment]
A next step could be to deprecate Sphinx and instead use only Doxygen with the [Doxygen Awesome](https://github.com/jothepro/doxygen-awesome-css) theme.

**Comment by aothms** [comment]
Thanks for this. It's great to have more eyes on the documentation output.

How did you invoke doxygen, did you test with this script https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/docs/generate_docs.py ?

> A next step could be to deprecate Sphinx and instead use only Doxygen with the [Doxygen Awesome](https://github.com/jothepro/doxygen-awesome-css) theme.

The reason for using sphinx is that we integrate the cpp docs with the python docs. See here where they are hosted side by side https://ifcopenshell.github.io/docs/

Is that still possible with your suggestion?

>  `NUM_PROC_THREADS       = 1`

Is it an idea to set this to 0 given how slow it is to currently build the cpp docs?

**Comment by dirkolbrich** [comment]
At first I am more interested in the C++ documentation and having a local one with nice diagrams available.

I don't really know how the process with Sphinx works and how you pull the different Python documentations of the numerous submodules into a single Sphinx build and after that combine this with the Doxygen output. From my first impression of the setup it seems overly complicated as a lot of modules have a separate `docs/` folder with its own `conf.py` and several `.rst` files. -> maybe a short tldr: describing the docs concept would help future devs

And there are linking errors. For example: I can publicly access the C++ documentation under https://ifcopenshell.github.io/docs/ which is linked from the [IfcOpenShell hompage](http://ifcopenshell.org). From there I can jump to the Python docs under https://ifcopenshell.github.io/docs/python/html/index.html. But once into the Python docs there is no link back to the C++ docs.

---

I started the local build within the `docs/` folder by issuing simply `doxygen Doxyfile`.  I did _not_ test the `generate_docs.py` script. The script should still work with this updated Doxyfile, as the generation of XML files ist not changed. The generated HTML files are placed alongside in its own `output/doxygen/html` folder.

>The reason for using sphinx is that we integrate the cpp docs with the python docs. See here where they are hosted side by side https://ifcopenshell.github.io/docs/
> Is that still possible with your suggestion?

IMV this should be possible as Doxygen can build documentation for C++ and Python code in one go, as it does with the FreeCAD documentation. I think using only doxagen would simplify the process -> I will look into if it how a possible setup would work.

> NUM_PROC_THREADS = 1
>
> Is it an idea to set this to 0 given how slow it is to currently build the cpp docs?

Actually I would set it higher to 3. After the local doxygen build is finished I receive the following info:
```
lookup cache used 65536/65536 hits=2739153 misses=426893
Note: based on cache misses the ideal setting for LOOKUP_CACHE_SIZE is 3 at the cost of higher memory usage.
finished...
```

**Comment by dirkolbrich** [comment]
@aothms Coming back to the docs, I'm now able to understand the build system for the docs a bit better and would like to help in updating and streamlining these.

- use Python or Cmake script to build the docs, both should yield the same result
- Cmake to build local Docs for C++ including all SVG graphs

What's the most convenient way for you to upload the docs. Or better, what are the settings that https://ifcopenshell.github.io/docs/ pulls it's documents from?

**Comment by Moult** [comment]
For the Python docs, there is https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifcopenshell-python/docs generated using Sphinx (`make html`). I've got a more up to date version of https://ifcopenshell.github.io/docs/python/html/index.html running on https://blenderbim.org/docs-python/ with what I personally think is a sexier theme, a much more comprehensive API Reference, and more up to date stuff on the other libs/cli apps (e.g. IfcDiff).

The BlenderBIM end-user docs, which may or may not be relevant, is in src/blenderbim/docs also using Sphinx and hosted here https://blenderbim.org/docs - I'd prefer one system to two doc generators, whichever it may be.

The process is equally simple and just a `make clean html`. There is only one line required in the config to pull in all the Python modules into the docs: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/docs/conf.py#L63 - you can see the conf.py file is also very minimal.

I'm rather agnostic of backend, so long as the theme is still sexy, it isn't a huge amount of work/formatting on the current RST doc files, and Doxygen can properly handle the Python API.

**Comment by dirkolbrich** [comment]
> I've got a more up to date version of https://ifcopenshell.github.io/docs/python/html/index.html running on https://blenderbim.org/docs-python/ with what I personally think is a sexier theme, a much more comprehensive API Reference, and more up to date stuff on the other libs/cli apps (e.g. IfcDiff).

I took a look and think this is very confusing for the docs reader. Which version for ifc is current and valid? How do I get from the ifcopenshell.org website to the blenderbim.org/docs-python website?
There should be only one ifcopenshell.org/docs/ related to anything IFC and one blenderbim.org/docs/ related to anything regarding the Blender Add-on.

- move ifcopenshell docs to the domain ifcopenshell.org/docs/ -> find a way for an automated build and move of the public files to ifcopenshell/website/docs repo and change the hardcoded link in the website header
- link from blenderbim.org/docs/devs/ to the ifcopenshell docs
- maybe use two distinctive themes between ifcopenshell (bright) and blenderbim (dark) which shows that these are two separate but interconnected projects

Let me try to find a setup which builds the ifcopenshell docs and blenderbim docs in one go (or separately if wanted). Maybe we can than find a way how to deploy automatically to the websites?

**Comment by Moult** [comment]
> Which version for ifc is current and valid?

What do you mean? Both the versions on IOS and the BlenderBIM.org domain come from the same source, just that the BlenderBIM.org one excludes the C++ stuff, has a different theme, and is more recent (and thus includes more Python stuff). You don't get from one to another - it's the same thing with different themes, built at different times.

Yes, the intention is to have BlenderBIM-specific docs hosted on the BlenderBIM.org site and the IOS docs on the IOS site, but our websites are [currently under construction](https://github.com/IfcOpenShell/website/issues/2) and I guess @aothms is pretty busy so I hosted a copy on the blenderbim.org domain too. If you can help setup the build process with @aothms so that it's all setup on the IOS domain, I'll take down the blenderbim.org mirror.

Does that help explain the situation?

**Comment by dirkolbrich** [comment]
> and is more recent (and thus includes more Python stuff)

That's what I mean with confusing. Both domains have the same docs from the same source BUT are build on different repo versions thus containing different information.

Yes, your explanation clarifies the current status. So the web docs are a kind of in a WIP/interim process and need work. Will see how I can help with that.

**Comment by Moult** [comment]
Indeed, we've been wanting to improve the web infra for a while now but we've just been so busy with the app coding itself it would be awesome if you wanted to join and help tackle this!

I'd say look at the IOS site as a reference for what the C++ sections of the doc should contain, and look at the BBIM site as a reference for what the Python and agnostic (i.e. non-code docs) sections of the doc should contain. I'd also personally say look at the BBIM site in terms of the intended theme and site structure and little details (e.g. "tips" and "see also" CSS styled sections).

When it is all consolidated, it would be good to also remove the README.md to just point to the better-formatted docs, and also link the automated builds to the docs so that the docs contain the appropriate links to the latest builds.

I can help with writing more docs too about the rest of the utils (ifcclash/ifcpatch/ifc4d/5d/etc) so at least the entry pages also look less empty.

**Comment by dirkolbrich** [comment]
I'd like to resurrect this issue for an overhauled C++ API docs.

As the source files of the current docs of https://ifcopenshell.org (which are linked under https://blenderbim.org/docs-python/) are located under `src/ifcopenshell-python/docs/` (which IMHO is a weird location), the `docs/` folder can be used for the IfcOpenShell core C++ API docs.

(a very old version of the C++ API docs from 2020 is online under https://ifcopenshell.github.io/docs/rst_files/library_root.html)

You can build the docs with the simple command `doxygen` from within the `docs/` folder (make sure you have doxygen and graphviz installed in your path). The resulting files are build within the `docs/output/doxygen/html/` folder. It might take a while as I have enabled svg graph generation.

I set up the docs to use the [doxygen-awesome](https://jothepro.github.io/doxygen-awesome-css/) theme for a more modern look than the doxygen default theme.

Bildschirmfoto 2023-09-21 um 20 39 19

**Comment by Moult** [comment]
> which IMHO is a weird location

Agreed. @aothms what do you think about having `/docs/cpp` and `/docs/python` or `docs/other` or something else?


BTW I'm incrementally writing docs / restructuring docs. If you haven't visited it lately check it out :) https://blenderbim.org/docs-python/

... we should also probably discuss hosting ifcopenshell docs on the ifcopenshell domain name :)

**Comment by dirkolbrich** [comment]
If you move it all into the `/docs` folder I probably would go with:
```shell
/docs
- ifcopenshell
- blenderbim
- cpp-api
- python-api
- README.md // <- documents the structure of the /docs folder
- some_script.sh // <- maybe build script for parts or all of the documentation from source
``` 
This way we can split the documentation into logical parts, yet keep them in a centralised folder.

**Comment by dirkolbrich** [comment]
Hi there, here my _now_ monthly reminder. Is there anything I can add to this PR to unblock the merge und move forward? I'm happy to discuss any changes you might have.

**Comment by aothms** [comment]
Just two questions. I see that the `doxygen-awesome-css` comes with quite some stuff. Should we either embed it as a submodule / include only the things we need / fetch it on demand when building?

```
docs/cpp-api/assets/doxygen-awesome-css/.github/workflows/publish.yaml
docs/cpp-api/assets/doxygen-awesome-css/.gitignore
docs/cpp-api/assets/doxygen-awesome-css/.npmignore
docs/cpp-api/assets/doxygen-awesome-css/LICENSE
docs/cpp-api/assets/doxygen-awesome-css/Makefile
docs/cpp-api/assets/doxygen-awesome-css/README.md
docs/cpp-api/assets/doxygen-awesome-css/docs/customization.md
docs/cpp-api/assets/doxygen-awesome-css/docs/extensions.md
docs/cpp-api/assets/doxygen-awesome-css/docs/img/darkmode_toggle.png
docs/cpp-api/assets/doxygen-awesome-css/docs/img/fancy_scrollbars_firefox.png
docs/cpp-api/assets/doxygen-awesome-css/docs/img/fancy_scrollbars_webkit.gif
docs/cpp-api/assets/doxygen-awesome-css/docs/img/fragment_copy_button.png
docs/cpp-api/assets/doxygen-awesome-css/docs/img/interactive_toc_mobile.png
docs/cpp-api/assets/doxygen-awesome-css/docs/img/paragraph_link.png
docs/cpp-api/assets/doxygen-awesome-css/docs/tricks.md
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-fragment-copy-button.js
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-interactive-toc.js
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-paragraph-link.js
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-sidebar-only.css
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome-tabs.js
docs/cpp-api/assets/doxygen-awesome-css/doxygen-awesome.css
docs/cpp-api/assets/doxygen-awesome-css/doxygen-custom/custom-alternative.css
docs/cpp-api/assets/doxygen-awesome-css/doxygen-custom/custom.css
docs/cpp-api/assets/doxygen-awesome-css/doxygen-custom/header.html
docs/cpp-api/assets/doxygen-awesome-css/doxygen-custom/toggle-alternative-theme.js
docs/cpp-api/assets/doxygen-awesome-css/img/screenshot.png
docs/cpp-api/assets/doxygen-awesome-css/img/testimage.png
docs/cpp-api/assets/doxygen-awesome-css/img/theme-variants.drawio.svg
docs/cpp-api/assets/doxygen-awesome-css/include/MyLibrary/example.hpp
docs/cpp-api/assets/doxygen-awesome-css/include/MyLibrary/subclass-example.hpp
docs/cpp-api/assets/doxygen-awesome-css/logo.drawio.svg
docs/cpp-api/assets/doxygen-awesome-css/package.json
```

I assume with duplicate you mean these, since you deleted them, but where are they now then?

```
docs/geom/images/settings-1.png
docs/geom/images/settings-2.png
docs/geom/images/settings-3.png
docs/geom/images/settings-4.png
docs/geom/images/settings-5.png
docs/geom/settings.md
```

**Comment by dirkolbrich** [comment]
> embed it as a submodule

You are right, that's the better way. It's even [documented in the installation guide](https://jothepro.github.io/doxygen-awesome-css/index.html#autotoc_md12). This was just laziness on my side. I will change it.

> I assume with duplicate you mean these, since you deleted them, but where are they now then?

The image files are located/duplicated under [src/ifcopenshell-python/docs/ifcopenshell/images](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifcopenshell-python/docs/ifcopenshell/images), the text file was moved and renamed to [src/ifcopenshell-python/docs/ifcopenshell/geometry_settings.rst](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/docs/ifcopenshell/geometry_settings.rst), all done with commit https://github.com/IfcOpenShell/IfcOpenShell/commit/72147e51f57f2ef07b1264d2e04b652fa09c98f4.

**Comment by aothms** [comment]
Thank you 🙏

**Comment by dirkolbrich** [comment]
👍🏻

**Pull request merged**
