### PR TITLE
update SF.net download URL

### LINKED ISSUE #374: win build script: SWIG download fails
Not sure whether this is just temporary, or maybe sourceforge has changed the URL a bit!?
https instead of http ??

https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L429-L444

https://sourceforge.net/projects/swig/files/swigwin/swigwin-3.0.12/

EDIT: Downloading manually works, the URL used was:
https://datapacket.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.12/swigwin-3.0.12.zip

EDIT: Documentation of the mirrors is here:
https://sourceforge.net/p/forge/documentation/Downloading%20files%20via%20the%20command%20line/

### PR DESCRIPTION
**Pull request by thorade**
This closes #374

### CODE REVIEW

**Comment by thorade** [comment]
Note: This points to a certain mirror, so I will just close it, and possibly re-open once I found how to point to a generic/permanent URL.

**Comment by thorade** [comment]
One has to use https with TLS1.2 now to download files from Sourceforge.

**Comment by thorade** [comment]
It seems that only Powershell >= 5.0 is able to do TLS 1.2,
so this possibly breaks the script for some users.
Whenever that happens, these users would have to manually download and install an up-to-date PowerShell!

**Comment by thorade** [comment]
As an alternative, one could just assume SWIG is installe dand on the path, just like git and CMake.

**Comment by Stinkfist0** [comment]
Could https://osdn.net/projects/sfnet_swig/releases/ be trusted for obtaining SWIG.

**Comment by thorade** [comment]
You could also download from here:
https://anaconda.org/conda-forge/swig/files
https://anaconda.org/anaconda/swig
But both OSDN and Anaconda also use https, so one would have to test what TLS level they require.

**Comment by aothms** [comment]
Thanks, sorry for the late reply. If powershell 5 is required. According to the table here [1] this would break the script for everybody not running Win 10. That sounds a bit harsh. Where did you read about the powershell version required for TLS 1.2?

[1] https://4sysops.com/wiki/differences-between-powershell-versions/

Alternatively we should probably at least detect this early on and prevent the same confusion you experienced. E.g. `powershell -c "exit $PSVersionTable.PSVersion.Major -lt 5"`

**Comment by thorade** [comment]
I think I read that in one the github issues or stackoverflow, e.g. here:
https://stackoverflow.com/a/36266139/874701
Apparently it depends on the .NET version used by powershell!?
But that is not "official", I can try to find an official source, or try to test the script on an older computer.

Also, it is possible to install the latest Powershell version also on older Windows, but it does not come preinstalled.

**Comment by aothms** [comment]
> I can try to find an official source, or try to test the script on an older computer.

Yeah I'm not sure how to proceed on this. Don't want to waste much time on this, but also don't want to upset users with cryptic error messages. Let's just merge this and see what happens. Thanks!

**Comment by Stinkfist0** [comment]
It would be nice to have the required Powershell documented here, and perhaps provide a download link it, https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L592

**Comment by aothms** [comment]
I agree and/or a check to see whether the required version is found: `powershell -c "exit $PSVersionTable.PSVersion.Major -lt 5"`

**Comment by thorade** [comment]
Download links are provided in the blog post that Thomas linked above:
https://4sysops.com/wiki/differences-between-powershell-versions/
https://www.microsoft.com/en-us/download/details.aspx?id=54616

Not sure where to put that check and corresponding output, otherwise I would send a PR.

**Comment by thorade** [comment]
Just tested on Windows 7, and the error message people would see now is similar to:
```powershell
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enumeration value
s. Specify one of the following enumeration values and try again. The possible enumeration values are "Ssl3, Tls"."
At line:2 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```
So, at least it is a bit more informative than before.

**Pull request merged**
