### PR TITLE
CITATION.cff file for BlenderBIM

### PR DESCRIPTION
**Pull request by Martin15135215**
See https://github.com/IfcOpenShell/IfcOpenShell/issues/3095

I did not know who all needs to be in as author. Help is welcome!

This is the first test case, after this is merged, i will start a PR for the next CITATION.cff

### CODE REVIEW

**Comment by aothms** [comment]
I don't know what is reasonable here, but I definitely don't deserve to be 2nd "author" ;)

```
$ git shortlog -n -s -- src/blenderbim src/ifcopenshell-python/ifcopenshell/api
  1702  Dion Moult
   324  Andrej730
   154  Sigma Dimensions
    80  Gorgious56
    71  Gorgious
    56  Vukas Pajic
    52  Massimo Fabbro
    37  bosonprojets
    31  Bruno Postle
    30  Jesusbill
    29  Carlos Villagrasa
    25  Ryan Schultz
    16  CyrilWaechter
    13  carlos
    12  Bruno Perdigão
    11  s-leger
     8  Cyril Waechter
     6  Laurens Oostwegel
     6  Trashman247
     6  maxfb87
     5  HassanEmam
     4  Martin15135215
     4  Thomas Krijnen
     3  Chun
     3  luz paz
     2  Andrej
     2  Long
     1  Andrea Ghensi
     1  ArturTomczak
     1  Einar Raknes
     1  Emad Aghajani
     1  Julien Moutinho
     1  Kai Zhu
     1  Nathan Hild
     1  ecke101
     1  htlcnn
     1  krande
     1  luzpaz
```

**Comment by Moult** [comment]
Every year for the past 4 years there have been between 10-20 contributors who have made >= 10 commits (and up to 50 contributors per year if you don't use the >= 10 commit filter), so I wonder if there is a way to just say "IfcOpenShell contributors" similar to how its already credited in the BlenderBIM Add-on: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/__init__.py#L26

**Comment by Martin15135215** [comment]
It is possible to just use "IfcOpenShell contributors", see https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#authors

```yaml
authors:
  - name: "IfcOpenShell contributors"
```

If this is the desicion, i can change it to it. Can i change this PR or do i need to close this PR and create a new one?

**Comment by Moult** [comment]
I'm happy for you to use "IfcOpenShell Contributors" for the BlenderBIM Add-on and other Python based things like ifcclash/ifcdiff/ifcpatch/ifccsv/etc. I guess @aothms has the call on the C++ side. All these utilities are pretty interconnected - like the BlenderBIM Add-on is used heavily to find bugs in IfcOpenShell-Core and develop core features like drawings, and vice versa, the development in the API / Utils / Tree / Voxelisation all make it possible to build things on top like IfcSverchok, IfcClash, ...

You can always just change this PR, PRs can be squashed / rebased.

**Comment by Martin15135215** [comment]
If you have time, can you add a new column “language” in the content's table in the README.md at https://github.com/IfcOpenShell/IfcOpenShell?

So for all the tools that are with python, I can start doing the CITATION.cff

Screenshot_20230605_084552

**Comment by Martin15135215** [comment]
The author is changed to  "IfcOpenShell contributors"  and if there are no other concerns, this PR can be merged :)

**Comment by aothms** [comment]
Thanks @Martin15135215 for driving this

**Comment by Moult** [comment]
Thanks @Martin15135215 ! All the ones marked with an asterisk are C++ except for `ifcopenshell-python` which is half C++ half Python.

**Pull request merged**
