### PR TITLE
Add docs export excel - read excel 

### PR DESCRIPTION
**Pull request by chuongmep**
Add Documentation totorial export - read metadata excel from IFC

### CODE REVIEW

**Comment by chuongmep** [comment]
Hi @Moult, I reviewed csv, it is unconvinion to review a large model. When we export to excel, all parameter and class easier to review, analyst. This is why I'm want add more to support for user. 
Regard .

**Comment by Moult** [comment]
I don't understand, what can this do that IfcCSV cannot do?

**Comment by chuongmep** [comment]
@Moult example :  some value of parameter include character '',

**Comment by Moult** [comment]
@chuongmep you can already do that, IfcCSV supports regex: https://blenderbim.org/docs-python/ifcopenshell-python/selector_syntax.html#getting-element-values

**Comment by chuongmep** [comment]
Hi @Moult , thank you for your help !I can't deny the usefulness of csv and other formats, but I'm sure it depends on the use case as to how easily the data can be shared to the end user.
Thank you.

**Comment by Moult** [comment]
IfcCSV is just the name - it supports reading/writing ODS, XLSX, and Pandas Dataframes, not just CSV by the way.

**Comment by chuongmep** [comment]
Hi @Moult , I will take look into that. thank you. If have any issue I will reopen request.

**Comment by chuongmep** [comment]
how you can export all data like my file excel @Moult  ?

**Comment by Moult** [comment]
Right now a single workbook only contains one sheet. That sounds like a nice feature to add. Would you like to help build it?

Right now IfcCSV also requires you specify each column instead of automatic expansion of possible properties. See #3434. Would you like to help build it?

**Comment by Moult** [comment]
I just realised it isn't really documented anywhere, so FYI the current general features of IfcCSV are:

 1. Custom filtering of elements to show on your spreadsheet
 2. Custom columns selecting data from attributes, psets, classifications, materials, locations, systems, and other relationships
 3. Querying commands to select Nth relationship, or count number of relationships
 4. Custom formatting like custom column titles, formatting rules like imperial number formatting for units, rounding numbers to nearest X, etc
 5. Grouping rows with grouping rules e.g. count totals, get average, sum each row, etc
 6. Sorting rules including multi column sort
 7. Custom values to show null, true/false, or empty strings
 8. Preserve formatting of pre-formatted spreadsheets
 9. CSV/XLS/ODS/PD support
 10. Both export and import data (to then edit the IFC based on the changes in the spreadsheet)
 11. Summary rows such as grand totals
 12. GUI integration in Blender
 13. Integration with SVG table generation so you can place schedules on drawings / sheets

**Comment by chuongmep** [comment]
I don't think can do mutiple dataframs with csv format, may be we should seperate to new class ? 
I will colaborate when I have free time.

**Comment by Moult** [comment]
Indeed, for CSV the behaviour would split out to multiple CSV files e.g. with a suffix. I'm closing this PR and tracking this in #4252.

**Comment by chuongmep** [comment]
For sure, I will following with that part. Thank you.

**Pull request closed without merging**
